[versions]

bleatkan = "0.7.+"
touchportalSDK = "8.3.+"

# 2.1.0 > 2.1.10
kotlin = "2.1.10"
# 1.10.1 > 1.10.2
coroutines = "1.10.2"

# 3.0.3 > 3.1.3
ktor = "3.1.3"
# 1.7.3 > 1.8.1
serialization-json = "1.8.1"

## Misc

# 3.17.0
commons-lang3 = "3.17.0"
# 4.5.0-M3 > 4.5.0
commons-collections4 = "4.5.0"
# 2.0.0
semver = "2.0.0"

## Logging

# 2.23.1 > 2.24.3
log4j = "2.24.3"
# 2.0.16 > 2.0.17
slf4j = "2.0.17"
# 7.0.6 > 7.0.7
kotlinLogging = "7.0.7"

## Testing

# 5.12.1 > 5.12.2
jUnit = "5.12.2"
# 1.13.14 > 1.13.17 > 1.14.2
mockk = "1.14.2"

## Build

gmazzoBuildconfig = "5.+"


[libraries]
# BleatKan https://github.com/DissonantAU/bleatkan
bleatkan = { module = "io.github.dissonantau:bleatkan", version.ref = "bleatkan" }

# Touch Portal
touchportal-plugin-sdk = { module = "com.christophecvb.touchportal:plugin-sdk", version.ref = "touchportalSDK" }
touchportal-plugin-sdk-processor = { module = "com.christophecvb.touchportal:plugin-sdk-annotations-processor", version.ref = "touchportalSDK" }

# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-bom
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugins-bom
kotlin-gradle-plugins-bom = { module = "org.jetbrains.kotlin:kotlin-gradle-plugins-bom", version.ref = "kotlin" }

# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-bom
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j" }
kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }

# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-bom
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "serialization-json" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json" }

# https://mvnrepository.com/artifact/io.ktor/ktor-bom
ktor-client-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-serialization = { module = "io.ktor:ktor-serialization" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock" }

## Misc
# https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }

# https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
apache-commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commons-collections4" }

# https://mvnrepository.com/artifact/net.swiftzer.semver/semver
semver = { module = "net.swiftzer.semver:semver", version.ref = "semver" }

## Logging

# https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-bom
log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl" }

# https://mvnrepository.com/artifact/org.slf4j/slf4j-bom
slf4j-bom = { module = "org.slf4j:slf4j-bom", version.ref = "slf4j" }
slf4j-api = { module = "org.slf4j:slf4j-api" }

# https://mvnrepository.com/artifact/io.github.oshai/kotlin-logging-jvm
logging-kotlin = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }

## Testing

# https://mvnrepository.com/artifact/org.junit/junit-bom
junit-bom = { module = "org.junit:junit-bom", version.ref = "jUnit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# https://mvnrepository.com/artifact/io.mockk/mockk
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-gradle = { id = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }

gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gmazzoBuildconfig" }
touchportal-plugin-packager = { id = "com.christophecvb.touchportal.plugin-packager", version.ref = "touchportalSDK" }

[bundles]
