package io.github.dissonantau.veadotubetouchportalplugin

import com.google.gson.JsonObject
import io.github.oshai.kotlinlogging.KotlinLogging
import java.util.concurrent.atomic.AtomicBoolean

import com.christophecvb.touchportal.TouchPortalPlugin
import com.christophecvb.touchportal.annotations.*
import com.christophecvb.touchportal.helpers.PluginHelper
import com.christophecvb.touchportal.model.*

import io.github.dissonantau.veadotubetouchportalplugin.data.VeadoConnectionData
import io.github.dissonantau.veadotubetouchportalplugin.data.VtState

import io.github.dissonantau.bleatkan.connection.Connection
import io.github.dissonantau.bleatkan.connection.ConnectionError
import io.github.dissonantau.bleatkan.connection.ConnectionListener
import io.github.dissonantau.bleatkan.instance.*
import io.github.dissonantau.bleatkan.message.VeadoRequest
import io.github.dissonantau.bleatkan.message.ResultMessage
import io.github.dissonantau.veadotubetouchportalplugin.updatechecker.*
import kotlinx.serialization.json.Json
import net.swiftzer.semver.SemVer
import kotlin.collections.ArrayList
import kotlin.collections.HashMap
import kotlin.collections.LinkedHashMap
import io.github.dissonantau.bleatkan.message.ResultPayload.ResultPayloadState as BleatkanStatePeek
import io.github.dissonantau.bleatkan.message.ResultPayload.ResultPayloadStateList as BleatkanStateList
import io.github.dissonantau.bleatkan.message.ResultPayload.ResultPayloadPng as BleatkanStateThumbnail


@Suppress("unused")
@Plugin(
    name = BuildConfig.NAME_SHORT, version = BuildConfig.VERSION_CODE,
    colorDark = "#5c1c1c", colorLight = "#822727"
)
class VeadoTouchPlugin(parallelizeActions: Boolean) :
    TouchPortalPlugin(parallelizeActions), TouchPortalPlugin.TouchPortalPluginListener,
    InstancesListener, ConnectionListener, UpdateCheckResultListener {


    companion object {
        /** Class Logger */
        @JvmStatic
        private val LOGGER =
            KotlinLogging.logger { TouchPortalPlugin::class.java.name }

        /**
         * Avatar State String RegEx
         *
         * Strings generated by [onUpdateAvatarStateList] are formatted "name (id)" and sent to Touch Portal
         *
         * This RegEx will extract the Name and ID to named groups, with space between Name and ID, and extra brackets excluded
         */
        @JvmStatic
        private val avatarStateRegex = """(?<name>.*?)?\s*\((?<id>\w+)\)""".toRegex()


        /**
         * Avatar State String RegEx
         *
         * Strings generated by [onUpdateAvatarStateList] are formatted "name (id)" and sent to Touch Portal
         *
         * This RegEx will extract the Name and ID to named groups, with space between Name and ID, and extra brackets excluded
         *
         * This Version can Handle Pre- and Post-2.1 Strings, where the ID now = Name
         *
         * It's only used for Deprecated ID Actions, as new 'By Name' Should expect Name only
         */
        @JvmStatic
        private val avatarStateRegexAny = """(?<name>.*?)? ?(?:\((?<id>.*)\))?""".toRegex()

        /** Veadotube Plugin Object */
        @JvmStatic
        private lateinit var veadotubePlugin: VeadoTouchPlugin

        /** Set Enabled when shutting down to prevent doubling up */
        @JvmStatic
        private var pluginClosing = AtomicBoolean(false)

        @JvmStatic
        fun main(args: Array<String>) {
            LOGGER.debug { "${BuildConfig.NAME} Launched with ${args.size} args: ${args.toList()}" }

            LOGGER.debug { "Kotlin Version            : ${KotlinVersion.CURRENT} " }
            LOGGER.debug { "Java Version              : ${System.getProperty("java.version")} " }
            LOGGER.debug { "Java VM Version           : ${System.getProperty("java.vm.version")} " }
            LOGGER.debug { "Java VM Vendor            : ${System.getProperty("java.vm.vendor")}  " }
            LOGGER.debug { "Java VM Name              : ${System.getProperty("java.vm.name")} " }
            LOGGER.debug { "Java VM Spec Version      : ${System.getProperty("java.vm.specification.version")}" }
            LOGGER.debug { "Java VM Spec Vendor       : ${System.getProperty("java.vm.specification.vendor")}" }
            LOGGER.debug { "Java VM Spec Name         : ${System.getProperty("java.vm.specification.name")}" }
            LOGGER.debug { "Java Runtime Spec Version : ${System.getProperty("java.specification.version")}" }
            LOGGER.debug { "Java Runtime Spec Vendor  : ${System.getProperty("java.specification.vendor")}" }
            LOGGER.debug { "Java Runtime Spec Name    : ${System.getProperty("java.specification.name")}" }

            if (args.size == 1) {

                if (PluginHelper.COMMAND_START == args[0]) {
                    LOGGER.info {
                        "${BuildConfig.NAME_SHORT} Starting - Plugin Version: ${
                            BuildConfig.VERSION_NAME_FULL
                        } - Java Version ${System.getProperty("java.version")}"
                    }

                    veadotubePlugin = VeadoTouchPlugin(true)

                    setUpShutdownHook()

                    // Initialize the Plugin
                    veadotubePlugin.initializePlugin()

                }

            }

        }

        @JvmStatic
        private fun setUpShutdownHook() {
            Runtime.getRuntime().addShutdownHook(object : Thread() {
                override fun run() {
                    LOGGER.info { "Plugin Shutting Down" }
                    // Start Shutdown
                    veadotubePlugin.shutdown()
                }
            })

        }


        /* Start of functions for Update Checks */

        /**
         * JSON De/serializer
         */
        private val jsonDeserializer = Json {
            ignoreUnknownKeys = true
            useAlternativeNames = false
        }

        fun calculateNextUpdateRelease(
            updateData: UpdateReleaseData,
            currentRelease: SemVer,
            recommendedBranchRelease: SemVer,
            updateCheckResult: UpdateCheckResult
        ) {

            val currentReleaseMajorVer = currentRelease.major
            val currentRecommendedIsSameMajorVer =
                currentReleaseMajorVer == recommendedBranchRelease.major

            // Scan Version list of Major Version for any Recommended Next Versions
            val versionListMapString = updateCheckResult.mainTrack.releaseMapByVersionString
            val versionListGroupMap = updateCheckResult.mainTrack.releaseListGroupMap

            // Try and get current version from the Release List
            versionListMapString[currentRelease.toString()]?.let { currentReleaseData ->
                // Release Matching Current found > Find Recommended release

                currentReleaseData.recommendedNextRelease?.let { recommendedNextString ->
                    // Recommended version found, get release info
                    versionListMapString[recommendedNextString]?.let {
                        updateData.mainBranchReleaseData = it;
                        updateData.mainBranchUpdateAvailable = true
                        updateData.mainBranchManualUpdateRequired = currentReleaseData.recommendedNextReleaseRequiresManualUpdate
                        return
                    }
                }
            }
            // Continues if Current Release doesn't have Recommended Next Release or version info not found


            // Go through update list and look for next recommended updates
            // the same major version track
            versionListGroupMap[currentReleaseMajorVer]?.listIterator()?.let { listIterator ->
                for (release in listIterator) {
                    // Skip if less than current
                    if (release.versionSemantic < currentRelease) continue
                    // If Next Ver is Same Major Version, break if we pass it
                    if (currentRecommendedIsSameMajorVer && release.versionSemantic > recommendedBranchRelease) break

                    // If we find an exact match for recommended version while scanning, return it
                    if (currentRecommendedIsSameMajorVer && release.versionSemantic == recommendedBranchRelease) {
                        updateData.mainBranchReleaseData = release;
                        updateData.mainBranchUpdateAvailable = true
                        return
                    }
                    // Try and find recommendedNextRelease - continues if string is null, or string doesn't match a next version
                    release.recommendedNextRelease?.let { recommendedNextString ->
                        // Recommended version found, get release info
                        versionListMapString[recommendedNextString]?.let {
                            updateData.mainBranchReleaseData = it;
                            updateData.mainBranchUpdateAvailable = true
                            updateData.mainBranchManualUpdateRequired = release.recommendedNextReleaseRequiresManualUpdate
                            return
                        }
                    }
                }
            }

            // If updateRelease not set by now, fall back to recommendedMainRelease
            versionListMapString[recommendedBranchRelease.toString()]?.let {
                updateData.mainBranchReleaseData = it
                updateData.mainBranchUpdateAvailable = true
            }
        }


        fun calculateNextUpdateDev(
            updateData: UpdateReleaseData,
            currentRelease: SemVer,
            recommendedMainBranchRelease: SemVer?,
            recommendedDevBranchRelease: SemVer?,
            updateCheckResult: UpdateCheckResult
        ) {
            // If recommended releases are the same, return null (Main Ver check returns same)
            if (recommendedMainBranchRelease == recommendedDevBranchRelease) {
                //updateData.devBranchReleaseData = null
                return
            }

            // If null, we can't find any recommended updates (Also smart casts to non-nullable
            if (updateCheckResult.devTrack == null) {
                //updateData.devBranchReleaseData = null
                return
            }

            val currentReleaseMajorVer = currentRelease.major

            val currentRecommendedDevSameMajorVer =
                currentReleaseMajorVer == recommendedDevBranchRelease?.major

            // Try and get current version from the Release List
            updateCheckResult.devTrack.releaseMapByVersionString[currentRelease.toString()]
                ?.let { currentReleaseData ->
                    // Release Matching Current found > Find Recommended release

                    currentReleaseData.recommendedNextRelease?.let { recommendedNextString ->
                        // Recommended version found, get release info
                        updateData.devBranchReleaseData =
                            getMainOrPreReleaseByVersionString(
                                recommendedNextString,
                                updateCheckResult.mainTrack,
                                updateCheckResult.devTrack
                            )
                        updateData.devBranchUpdateAvailable = true
                        updateData.devBranchManualUpdateRequired =
                            currentReleaseData.recommendedNextReleaseRequiresManualUpdate
                        return
                    }
                }
            // Continues if Current Release doesn't have Recommended Next Release or version info not found


            val versionListGroupMap = updateCheckResult.devTrack.releaseListGroupMap
            var recommendedVersionString: String? = null
            var recommendedVersionStringRequiresManualUpdate = false

            // Go through update list and look for next recommended updates
            // the same major version track
            versionListGroupMap[currentReleaseMajorVer]?.listIterator()?.let { listIterator ->
                for (release in listIterator) {
                    // Skip if less than current
                    if (release.versionSemantic < currentRelease) continue

                    // If Next Ver is Same Major Version, break if we pass it
                    if (currentRecommendedDevSameMajorVer &&
                        (recommendedDevBranchRelease != null && release.versionSemantic > recommendedDevBranchRelease)
                    ) break

                    // If we find an exact match for recommended version while scanning, return it
                    if (currentRecommendedDevSameMajorVer && release.versionSemantic == recommendedDevBranchRelease) {
                        updateData.devBranchReleaseData = release
                        return
                    }

                    // Try and find recommendedNextRelease
                    if (release.recommendedNextRelease != null) {
                        // Recommended version found, get release info
                        recommendedVersionString = release.recommendedNextRelease
                        recommendedVersionStringRequiresManualUpdate =
                            release.recommendedNextReleaseRequiresManualUpdate
                        break
                    }
                }
            }


            // Ver string - check if pre-release, then try and find the version and return
            recommendedVersionString?.let { recommendedVerString ->
                updateData.devBranchReleaseData =
                    getMainOrPreReleaseByVersionString(
                        recommendedVerString,
                        updateCheckResult.mainTrack,
                        updateCheckResult.devTrack
                    )
                updateData.devBranchUpdateAvailable = true
                updateData.devBranchManualUpdateRequired = recommendedVersionStringRequiresManualUpdate
                return
            }

        }

        /**
         * Checks semVerString:
         * - If pre-release semVer, looks in devBranchData.releaseMapByVersionString for Release matching String.
         * - If not pre-release semVer, looks in mainBranchData.releaseMapByVersionString for Release matching String.
         *
         * If no match found, returns null
         */
        fun getMainOrPreReleaseByVersionString(
            semVerString: String,
            mainBranchData: ReleaseBranchData,
            devBranchData: ReleaseBranchData
        ): ReleaseData? {
            return if (semVerStringIsPreRelease(semVerString))
                devBranchData.releaseMapByVersionString[semVerString]
            else // Isn't Pre-release
                mainBranchData.releaseMapByVersionString[semVerString]
        }

        /**
         * Quick check for seeing if SemVer String is pre-release (has a dash before any +)
         *
         * e.g.
         * - 1.2.3-beta -> IS Pre-Release
         * - 1.2.3+abc-123 -> IS ***NOT*** Pre-Release
         * - 1.2.3-beta+abc-123 -> IS Pre-Release
         *
         */
        fun semVerStringIsPreRelease(semVerString: String): Boolean {
            val dashPos = semVerString.indexOf('-')
            if (dashPos > 0) {
                // If String contains dash, could be a pre-release
                val plusPos = semVerString.indexOf('+')

                // Plus also exists, and isn't after first dash - definitely pre-release
                return (plusPos < 0 || dashPos < plusPos)
            }
            return false
        }

        /* End of functions for Update Checks */

    }


    private fun initializePlugin() {
        LOGGER.trace { "initializePlugin: Start" }

        // Initiate the connection with the Touch Portal Plugin System
        val connectedPairedAndListening = connectThenPairAndListen(this)


        if (connectedPairedAndListening) {
            LOGGER.info { "Plugin with ID[${VeadoTouchPluginConstants.ID}] Connected and Paired!" }

        } else {
            LOGGER.error { "Failed to Connect and Pair with Touch Portal" }
            throw IllegalStateException("Failed to Connect and Pair with Touch Portal")
        }

        LOGGER.trace { "initializePlugin: Done" }
    }


    /* Touch Portal Categories */

    @Suppress("unused")
    enum class Categories {
        /**
         * Category definition example
         */
        @Category(
            name = "Veadotube - Primary Instance",
            imagePath = "images/icon-24.png"
        )
        PrimaryInstance

    }


    /* Touch Portal Settings Panel */
    /**
     * Setting - Show # of connected instances
     */
    @Setting(name = "# of Connected Instances", defaultValue = "0", isReadOnly = true)
    private var settingVeadoInstanceCount: String = "0"

    /**
     * Setting - Show Primary Instance Address
     */
    @Setting(name = "Primary Instance Address", defaultValue = "Plugin Starting", isReadOnly = true)
    private var settingVeadoPrimaryInstanceServer: String = "Plugin Starting"

    /**
     * Setting - Show Primary Instance Name
     */
    @Setting(name = "Primary Instance Name", defaultValue = "Plugin Starting", isReadOnly = true)
    private var settingVeadoPrimaryInstanceName: String = "Plugin Starting"

    /**
     * Setting - Primary Instance Name Overwrite
     */
    @Setting(name = "Primary Instance Name Override (Leave Blank to Disable)", defaultValue = "")
    private var settingVeadoPrimaryInstanceNameOverride: String = ""

    /**
     * Setting - Primary Instance Name Overwrite Existing Value
     *
     * Need to use this to know what the old/existing value is due to TP SDK replacing the setting automatically,
     * bypassing Kotlin Set and not allowing a comparison of old vs new
     */
    private var settingVeadoPrimaryInstanceNameOverrideExisting: String = ""

    /**
     * Setting - Auto Request Current State Thumbnail
     *
     * Enabled/Disabled (Currently Text due to v6 API - switch to Switch in v10)
     */
    @Setting(name = "Auto Request Current State Thumbnail (Enabled/Disabled)", defaultValue = "disabled")
    private var settingVeadoAutoRequestThumbnail: String = "disabled"


    /**
     * Setting - Auto Request Current State Thumbnail Existing Value
     *
     * Enabled/Disabled (Currently Text due to v6 API - switch to Switch in v10)
     */
    private var settingVeadoAutoRequestThumbnailExisting: String = "disabled"

    /**
     * Setting - Auto Request Current State Thumbnail
     *
     * Enabled/Disabled (Currently Text due to v6 API - switch to Switch in v10)
     */
    private var settingVeadoAutoRequestThumbnailEnabled = false


    /* Touch Portal States, Events, etc. */
    /**
     * Current Avatar State - `Name` (`ID`) Format
     */
    @State(
        desc = "Current Avatar State - Name & ID (Deprecated)",
        defaultValue = "Not Connected",
        categoryId = "PrimaryInstance",
        id = "currentAvatarState"
    )
    private var stateCurrentAvatarState: String = "Not Connected"


    /**
     * Current Avatar State ID
     */
    @State(
        desc = "Current Avatar State - ID (Deprecated)",
        defaultValue = "Not Connected",
        categoryId = "PrimaryInstance",
        id = "currentAvatarStateId"
    )
    private var stateCurrentAvatarStateId: String = "Not Connected"


    /**
     * Current Avatar State - Name
     */
    @State(
        desc = "Current Avatar State - Name",
        defaultValue = "Not Connected",
        categoryId = "PrimaryInstance",
        id = "currentAvatarStateName"
    )
    private var stateCurrentAvatarStateName: String = "Not Connected"


    /**
     * Current Avatar State - Thumbnail
     */
    @State(
        desc = "Current Avatar State - Thumbnail",
        defaultValue = "",
        categoryId = "PrimaryInstance",
        id = "currentAvatarStateThumbnail"
    )
    private var stateCurrentAvatarStateThumbnail: String = ""


    /**
     * Set Current Avatar State with State ID String in 'Name (ID)' Format (Mini 2.0) or just Name (Mini 2.1+)
     */
    @Action(
        name = "Set Avatar State from List",
        format = "Set Avatar State to {\$choices\$}",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setAvatarStateFromList"
    )
    private fun actionSetAvatarStateFromList(@Data(valueChoices = [""]) choices: Array<String>) {
        val connection = primaryConnection
        if (connection != null) {
            //Get State Object ID from String
            try {
                val newState = findAvatarFromStateString(connection, choices[0])

                if (newState != null) {
                    connection.send(channelNodes, VeadoRequest.createSetStateMini(newState.id))
                    LOGGER.debug {
                        "actionSetAvatarStateFromList: Set to '${choices[0]}'"
                    }
                } else {
                    LOGGER.warn { "Avatar Choice not Found: ${choices[0]}" }
                }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to send Set Avatar State From List: ${ex.message}" }
            }
        } else {
            LOGGER.warn { "Set Avatar State by Name: No connection, can't set Set Avatar to '${choices[0]}'" }
        }
    }


    /**
     * Set Current Avatar State Name
     *
     * Message from
     */
    @Action(
        name = "Set Avatar State by Name",
        format = "Set Avatar to State with Name {\$text\$}",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setAvatarStateByName"
    )
    private fun actionSetAvatarStateByName(@Data text: String) {
        val connection = primaryConnection
        if (connection != null) {
            val stateChange =
                if (connection.compatibilityFlagMiniPre2dot1) {
                    // Get connection states, find name
                    collConnectionData[connection]?.getStateByNameCompat(text)?.name
                } else {
                    text.trim()
                }

            if (stateChange == null) {
                LOGGER.warn { "Set Avatar State by Name: Can't find Name match for '$text'" }
                return
            }
            try {
                connection.send(channelNodes, VeadoRequest.createSetStateMini(stateChange))
                LOGGER.debug { "actionSetAvatarStateByID: Set ${connection.server} Avatar to '$text'" }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to send Set Avatar State By Name for ${connection.connUri}: ${ex.message}" }
            }
            return
        } else {
            LOGGER.warn { "Set Avatar State by Name: No connection, can't set Set Avatar to '$text'" }
        }
    }


    /**
     * Set Current Avatar State ID
     *
     * Deprecated from Mini 2.1
     */
    @Action(
        name = "Set Avatar State by ID (Mini 2.0)",
        format = "Set Avatar to State with ID {\$text\$} (Deprecated from Mini 2.1)",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setAvatarStateByID"
    )
    private fun actionSetAvatarStateByID(@Data text: String) {
        val connection = primaryConnection
        if (connection != null) {
            try {
                connection.send(channelNodes, VeadoRequest.createSetStateMini(text.trim()))
                LOGGER.debug { "actionSetAvatarStateByID: Set ${connection.server} Avatar to $text" }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to send Set Avatar State By ID for ${connection.connUri}: ${ex.message}" }
            }
        } else {
            LOGGER.warn { "Set Avatar State by ID: No connection, can't set Set Avatar to '$text'" }
        }
    }


    /**
     * Set Push To Talk/Mute input
     *
     * Enabling Push to Talk Mutes until the PTT Hotkey is pressed
     *
     */
    @Action(
        name = "Push-to-Talk Mic Input",
        format = "{\$choices\$} veadotube Push-to-Talk Microphone Input",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setPushToTalkMicInput"
    )
    private fun actionSetPushToTalkMicInput(@Data(valueChoices = ["Toggle", "Unmute", "Mute"]) choices: Array<String>) {
        LOGGER.debug { "actionSetPushToTalkMicInput: Set to '${choices[0]}'" }
        val connection = primaryConnection
        if (connection != null) {
            try {
                when (choices[0]) {
                    "Toggle" -> sendRequestPushToTalkMicInput(connection, null)
                    "Unmute" -> sendRequestPushToTalkMicInput(connection, true) // Prev Enable
                    "Mute" -> sendRequestPushToTalkMicInput(connection, false) // Prev Disable
                }
            } catch (ex: Exception) {
                LOGGER.debug { "actionSetPushToTalkMicInput: Error sending message ${ex.message}" }
            }

        }
    }


    /**
     * Send Custom JSON Request
     *
     */
    @Action(
        name = "Send Custom JSON Request",
        format = "Send JSON Request to Primary Instance - Channel:{\$channel\$}\nJSON:{\$json\$}",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "actionSendCustomJsonRequest"
    )
    private fun actionSendCustomJsonRequest(@Data channel: String, @Data json: String) {
        val connection = primaryConnection
        if (connection != null) {
            try {
                connection.send(channel, json)
                LOGGER.debug { "actionSendCustomJsonRequest: Sent ${connection.server} message: '$channel:$json'" }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to Send Custom JSON Request '$channel:$json' for ${connection.connUri}: ${ex.message}" }
            }
        } else {
            LOGGER.warn { "Send Custom JSON Request: No connection, can't send message: '$channel:$json'" }
        }
    }


    /* Main Vars */
    /**
     * Veadotube Instance Manager
     *
     * Reads Veadotube Instance Directory,
     *  alerts supplied [InstancesListener] (this) of changes
     */
    private var instanceManager: InstancesManager? = null


    /**
     * Veadotube Instance Collection
     *
     * String = [InstanceID.toString] Value
     *
     * Instance = Map of [Instance.instanceConnectionID] vs Instance Objects
     *
     * Should be run in a Synchronized context
     */
    private val instanceMap = HashMap<String, LinkedHashMap<String, Instance>>()

    /**
     * Veadotube Connection Collection
     *
     * String - [InstanceID.toString] Value
     *
     * Connection - Connection Map [Connection].[Instance.title] vs [Connection]
     *
     * Should be run in a Synchronized context
     */
    private val collInstConnections =
        HashMap<String, LinkedHashMap<String, Connection>>()

    /**
     * Map of [Connection]s with related [VeadoConnectionData]
     *
     * Contains data collected from Connection
     *
     * Work on held objects with should be synchronized with the [Connection] to prevent issues.
     *
     */
    private val collConnectionData =
        HashMap<Connection, VeadoConnectionData>()

    /**
     * Oldest instance by Launch time
     *
     * Used to work out Primary Connection
     */
    private var oldestInstance: Instance? = null

    /**
     * Primary Connection
     *
     * Used for actions etc. that don't specify a Connection
     *
     * Is Connection of Oldest Instance by default, or a match
     */
    private var primaryConnection: Connection? = null


    /**
     * Creates an Avatar State String from a State
     *
     * In the format of "`name` (`id`)"
     *
     * Note: Not needed 2.1 and later
     *
     * @param state State to Generate String from
     */
    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("2.1 removes separate ID")
    private fun avatarStateToString(state: VtState) =
        "${state.name} (${state.id})"


    /**
     * Creates an Avatar State String from a State Name and ID
     *
     * In the format of "`name` (`id`)"
     *
     * Note: Not needed 2.1 and later
     *
     * @param stateId ID to Generate String from
     * @param stateName Name to Generate String from
     */
    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("2.1 removes separate ID")
    private fun avatarStateToString(stateId: String, stateName: String) =
        "$stateName ($stateId)"


    /**
     * Updates the Avatar States for a Connection/Veadotube Instance in
     *
     * @param connection Connection where List was updated
     */
    @Suppress("DEPRECATION")
    private fun onUpdateAvatarStateList(connection: Connection) {
        val choices: ArrayList<String> = ArrayList()
        val choicesId: ArrayList<String> = ArrayList()

        /* primary Instance Choices*/
        // Oldest ID is primary
        val oldestInstanceID: InstanceID? = oldestInstance?.id

        val collectionsStates: ArrayList<VtState>? =
            collConnectionData[connection]?.statesAll

        if (!collectionsStates.isNullOrEmpty()) {
            for (state in collectionsStates) {

                val stateString = if (connection.compatibilityFlagMiniPre2dot1) {
                    // Generate String with Name and ID - pre 2.1
                    avatarStateToString(state)
                } else {
                    // ID is just name
                    state.id
                }

                LOGGER.trace { "updateAvatarState: Added Choice \"$stateString\"" }
                choices.add(stateString)
                choicesId.add(state.id)
            }
        }


        if (oldestInstanceID == connection.instance.id) {
            // Update State Choice for primary State Chooser
            sendChoiceUpdateCurrentAvatarState(choices)
        }

    }


    /** Dynamic State - Updated
     *
     * May be removed
     */
    private fun triggerAvatarUpdatedEvent(
        state: String = "Unknown",
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        this.sendCreateState(
            /* categoryId = */ "CategoryVeadotube",
            /* stateId = */ "avatarStateUpdated",
            /* parentGroup = */ "Veadotube",
            /* description = */ "Avatar State Updated",
            /* value = */ state,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )
    }


    /**
     * Extracts the ID from an Avatar State String and returns the matched Avatar State
     *
     * Returns a [VtState] if a match is found, `null` if not
     */
    private fun findAvatarFromStateString(connection: Connection, avatarStateString: String): VtState? {
        // Default Format is "<Name> (<ID>)" where ID is the State ID

        // State ID is different pre 2.1 - from 2.1 it's just the name
        val stateID = if (connection.compatibilityFlagMiniPre2dot1) {
            // Extract ID - pre 2.1
            findAvatarIDFromStatusString(avatarStateString) ?: return null
        } else {
            // ID is just name
            avatarStateString.trim()
        }

        val matchedState = collConnectionData[connection]?.getStateByID(stateID)

        LOGGER.debug {
            if (matchedState != null) {
                "findAvatarFromStateString: State Matched -> '${matchedState.id}', '${matchedState.name}'"
            } else {
                "findAvatarFromStateString: State '$stateID' not matched"
            }
        }

        return matchedState
    }


    /**
     * Extracts the ID from an Avatar State String and returns value
     *
     * Returns the Extracted ID if a match is found, `null` if not
     */
    private fun findAvatarIDFromStatusString(avatarStateString: String): String? {
        // Default Format is "<Name> (<ID>)" where ID is the State ID

        val matches = avatarStateRegex.find(avatarStateString)

        if (matches == null)
            LOGGER.warn { "findAvatarIDFromStatusString: Invalid Avatar State String: '$avatarStateString'" }
        else
            LOGGER.debug { "findAvatarIDFromStatusString: Regex found -> Name='${matches.groups["name"]?.value}' ID='${matches.groups["id"]?.value}'" }

        return matches?.groups?.get("id")?.value
    }


    /* Actions */
    @Action(name = "Refresh Avatar State List", categoryId = "PrimaryInstance", prefix = "Veadotube Mini")
    fun refreshStateListAll() {
        LOGGER.info { "refreshStateListAll" }

        synchronized(collInstConnections) {
            //request update from all channels
            collInstConnections.values.flatMap { it.values }.forEach {
                try {
                    it.send(channel = channelNodes, VeadoRequest.getListStateMini)
                    it.send(channel = channelNodes, VeadoRequest.getPeekStateMini)
                } catch (ex: Exception) {
                    LOGGER.warn { "Failed to Refresh Avatar State List for ${it.connUri}: ${ex.message}" }
                }
            }
        }
    }


    @Action(name = "Refresh Current Avatar State", categoryId = "PrimaryInstance", prefix = "Veadotube Mini")
    fun getAvatarStateAll() {
        LOGGER.info { "getAvatarStateAll triggered" }

        synchronized(collInstConnections) {
            //request update from all channels
            collInstConnections.values.flatMap { it.values }.forEach {
                LOGGER.debug { "getAvatarStateAll: send request triggered - channel $channelNodes; request ${VeadoRequest.getPeekStateMini}" }
                try {
                    it.send(channel = channelNodes, VeadoRequest.getPeekStateMini)
                } catch (ex: Exception) {
                    LOGGER.warn { "Failed to Refresh Current Avatar State for ${it.connUri}: ${ex.message}" }
                }
            }
        }
    }


    /**
     * Carries out shutdown, makes sure everything closes gracefully
     */
    private fun shutdown() {
        if (pluginClosing.getAndSet(true)) {
            return
        }

        runCatching { instanceManager?.close() }
        runCatching { Connection.closeAll() }

        if (veadotubePlugin.isConnected) {
            veadotubePlugin.close(null)
        }
    }


    /* Call Backs */
    override fun onDisconnected(exception: Exception?) {
        LOGGER.trace {
            when (exception) {
                null ->
                    "onDisconnected received"

                else ->
                    "onDisconnected received - exception: $exception"
            }
        }

    }


    override fun onReceived(jsonMessage: JsonObject) {
        // For unmapped actions, etc.
        LOGGER.debug { "onReceived - unexpected: $jsonMessage." }
    }


    override fun onListChanged(tpListChangeMessage: TPListChangeMessage) {
        LOGGER.debug { "onListChanged - unexpected: ${tpListChangeMessage.listId};${tpListChangeMessage.instanceId};${tpListChangeMessage.actionId};${tpListChangeMessage.value};" }
    }


    override fun onInfo(tpInfoMessage: TPInfoMessage) {
        LOGGER.debug { "onInfo ${tpInfoMessage.status}; ${tpInfoMessage.settings}" }

        if (tpInfoMessage.status == "paired") {

            LOGGER.debug { "Plugin ${BuildConfig.NAME_SHORT} - Started and Connected to Touch Portal" }

            LOGGER.debug { "Plugin Version Full Name:      ${BuildConfig.VERSION_NAME_FULL}" }

            LOGGER.debug { "Plugin Java VM Version:        ${System.getProperty("java.version")}" }

            LOGGER.debug {
                "Plugin Version Code / Base:    ${
                    BuildConfig.VERSION_CODE.toString().padStart(4, '0')
                } / ${BuildConfig.VERSION_NAME_BASE}"
            }
            LOGGER.debug { "Plugin is Build Release:       ${BuildConfig.BUILD_IS_RELEASE}" }
            if (!BuildConfig.BUILD_IS_RELEASE)
                LOGGER.debug { "Plugin Pre-release Version:    ${BuildConfig.BUILD_PRE_RELEASE_VERSION}" }

            LOGGER.debug { "Plugin Build Resources Bundle: ${BuildConfig.BUILD_RESOURCES_BUNDLE}" }

            LOGGER.debug { "Plugin Update/Releases URI:    ${BuildConfig.UPDATE_CHECK_RELEASES_URI}" }


            // Start Instance Manager - Watches Veadotube Instance Folder and sends events to the receiver
            LOGGER.trace { "Construct Instance Manager" }
            instanceManager = InstancesManager(this)


            //Initialize Avatar State Updated Event
            triggerAvatarUpdatedEvent()

            updateTPConnectionSettingInfo()

            // Run Plugin Update Check
            runUpdateCheck()
        }
    }

    private var updateChecker: PluginUpdateChecker? = null

    /**
     * Check for newer Plugin Versions
     */
    private fun runUpdateCheck() {
        updateChecker = PluginUpdateChecker(veadotubePlugin, BuildConfig.UPDATE_CHECK_RELEASES_URI)
    }

    /**
     * Process Received Update Check Result
     */
    override fun onUpdateCheckResult(resultData: UpdateCheckResult) {

        //Calculate Update Version(s)
        val updateData = calculateUpdates(resultData)


        if (updateData.updateAvailable) {
            // TODO Send notification
            // Check flagged as Manual (eg Breaking update) > updateManualRequired = true

            when {
                updateData.mainBranchReleaseData != null && updateData.devBranchReleaseData != null -> {
                    // Both Exist (Dev Version has update, Main also has update

                }

                updateData.mainBranchReleaseData != null && updateData.devBranchReleaseData == null -> {
                    // Both Exist (Dev Version has update, Main also has update

                }

                updateData.mainBranchReleaseData == null && updateData.devBranchReleaseData != null -> {
                    // Both Exist (Dev Version has update, Main also has update

                }

                else -> {
                    // Neither Exist - shouldn't reach this
                    LOGGER.warn { "Update Check has no release data but updateAvailable is true" }
                }

            }


        }

        // De-reference updateChecker
        updateChecker = null
    }


    /**
     * Process Received Update Check Error
     */
    override fun onUpdateCheckError(exception: Exception) {
        // Error
        LOGGER.error { "Error Checking for Updates: ${exception.message}" }
        LOGGER.debug { "onUpdateCheckError - ${exception.message} : ${exception.stackTraceToString()}" }
        // TODO Add some logic to display notification if Check fails over several runs
    }

    private fun updatePrimaryConnection(primaryNameOverwriteUpdated: Boolean = false) {
        if (instanceMap.isEmpty()) {
            oldestInstance = null
            primaryConnection = null
            return
        }

        if (oldestInstance == null) {
            synchronized(instanceMap) {
                updateOldestInstance()
            }
        }

        synchronized(collInstConnections) {
            synchronized(instanceMap) {

                if (oldestInstance != null) {
                    if (primaryConnection?.isConnected != true) primaryConnection = null // primary is not connected

                    val needsUpdate = when {
                        primaryNameOverwriteUpdated -> true
                        primaryConnection == null -> true
                        (settingVeadoPrimaryInstanceNameOverride.isBlank() &&
                                primaryConnection?.instance != oldestInstance) -> true

                        (settingVeadoPrimaryInstanceNameOverride.isNotEmpty() &&
                                primaryConnection?.instance?.title?.contains(
                                    settingVeadoPrimaryInstanceNameOverride,
                                    ignoreCase = false
                                ) != true) -> true

                        else -> false
                    }

                    if (needsUpdate) {

                        if (settingVeadoPrimaryInstanceNameOverride.isNotEmpty()) {
                            // Primary Overwrite Name was Updated, Name is NOT empty

                            val newPrimaryConnection =
                                collInstConnections.values.flatMap { it.values }
                                    .filter {
                                        it.name.contains(
                                            settingVeadoPrimaryInstanceNameOverride,
                                            ignoreCase = false
                                        )
                                    }.minByOrNull { it.connectionTimeMillis }

                            if (newPrimaryConnection != null) {
                                when (newPrimaryConnection) {
                                    primaryConnection -> { // Not Null, but Same
                                        LOGGER.trace { "Primary Instance left as '${newPrimaryConnection.instance.server}'; '${newPrimaryConnection.instance.title}'" }
                                    }

                                    else -> { // Not Null & Different
                                        primaryConnection = newPrimaryConnection
                                        LOGGER.info { "Primary Instance Updated to '${newPrimaryConnection.instance.server}'; '${newPrimaryConnection.instance.title}'" }
                                    }
                                }
                                return
                            }

                            // Continues as newPrimaryConnection was null
                            LOGGER.info { "Unable to find a match the Instance Override: '$settingVeadoPrimaryInstanceNameOverride'" }
                        }


                        if (primaryConnection == null ||
                            (settingVeadoPrimaryInstanceNameOverride.isBlank() &&
                                    primaryConnection?.instance != oldestInstance)
                        ) {
                            // If no Override (or Override not matched) find oldest
                            val newPrimaryConnectionFallback =
                                collInstConnections[oldestInstance?.id?.toString()]?.values?.minByOrNull { it.connectionTimeMillis }

                            when {
                                newPrimaryConnectionFallback == null -> {
                                    primaryConnection = null
                                    LOGGER.info { "Unable to find a Primary Connection" }
                                }

                                newPrimaryConnectionFallback != primaryConnection -> {
                                    // Not Null & Different
                                    primaryConnection = newPrimaryConnectionFallback
                                    LOGGER.info { "Primary Instance Updated to '${newPrimaryConnectionFallback.instance.server}'; '${newPrimaryConnectionFallback.instance.title}'" }
                                }

                                else -> {
                                    // Not Null, but Same
                                    LOGGER.trace { "Primary Instance left as '${newPrimaryConnectionFallback.instance.server}'; '${newPrimaryConnectionFallback.instance.title}'" }
                                }
                            }

                        }
                    }

                }

            }
        }

        updateTPConnectionSettingInfo()
    }


    /**
     * Requests [stateCurrentAvatarStateId] from [primaryConnection]
     */
    @Deprecated(
        "Use sendRequestStateThumbnail with primaryConnection as value",
        ReplaceWith("sendRequestStateThumbnail")
    )
    private fun sendRequestCurrentStateThumbnail() = kotlin.runCatching {
        primaryConnection?.let {
            if (stateCurrentAvatarStateId.isNotBlank()) {
                try {
                    primaryConnection?.send(
                        channel = channelNodes,
                        requestData = VeadoRequest.createThumbnailStateMini(stateCurrentAvatarStateId)
                    )
                } catch (ex: Exception) {
                    LOGGER.warn { "Failed to Request Current Avatar State Thumbnail for ${it.connUri}: ${ex.message}" }
                }
            }
        }
    }


    private fun updateTPConnectionSettingInfo() {
        synchronized(collInstConnections) {
            // Update connected Instances Count
            val connectedInstanceCount = collInstConnections.values.flatMap { it.values }.count()

            this.sendSettingUpdate(
                VeadoTouchPluginConstants.Settings.SettingVeadoInstanceCount.NAME,
                connectedInstanceCount.toString(),
                false
            )

            // Update Default/Oldest Instance info
            val conn = primaryConnection

            if (conn != null) {

                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceServer.NAME,
                    /* value = */       conn.server,
                    /* allowEmptyValue = */ false
                )

                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceName.NAME,
                    /* value = */       conn.instance.title,
                    /* allowEmptyValue = */ false
                )
            } else {
                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceServer.NAME,
                    /* value = */       "Awaiting Connection to Veadotube",
                    /* allowEmptyValue = */ true
                )

                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceName.NAME,
                    /* value = */       "Awaiting Connection to Veadotube",
                    /* allowEmptyValue = */ true
                )
            }
        }
    }


    override fun onBroadcast(tpBroadcastMessage: TPBroadcastMessage) {
        LOGGER.trace { "onBroadcast ${tpBroadcastMessage.event}; ${tpBroadcastMessage.type}; ${tpBroadcastMessage.pageName}" }
    }


    override fun onSettings(tpSettingsMessage: TPSettingsMessage) {
        LOGGER.debug { "onSettings ${tpSettingsMessage.settings}" }

        if (settingVeadoPrimaryInstanceNameOverrideExisting != settingVeadoPrimaryInstanceNameOverride) {
            settingVeadoPrimaryInstanceNameOverrideExisting = settingVeadoPrimaryInstanceNameOverride

            updatePrimaryConnection(true)
        }


        if (settingVeadoAutoRequestThumbnailExisting != settingVeadoAutoRequestThumbnail) {
            settingVeadoAutoRequestThumbnailExisting = settingVeadoAutoRequestThumbnail

            if (
                settingVeadoAutoRequestThumbnail.isNotBlank() && (
                        settingVeadoAutoRequestThumbnail.contains("en", ignoreCase = true) ||
                                settingVeadoAutoRequestThumbnail.contains("y", ignoreCase = true) ||
                                settingVeadoAutoRequestThumbnail.contains("tr", ignoreCase = true)
                        )
            ) {

                if (!settingVeadoAutoRequestThumbnailEnabled) {
                    settingVeadoAutoRequestThumbnailEnabled = true
                    //Send Peek request - when the reply is received, png will be checked, etc.
                    primaryConnection?.let { sendRequestStatePeek(it) }
                }

            } else {
                settingVeadoAutoRequestThumbnailEnabled = false
            }

        }
    }


    override fun onNotificationOptionClicked(tpNotificationOptionClickedMessage: TPNotificationOptionClickedMessage) {
        LOGGER.info { "onNotificationOptionClicked received" }
    }


    /* Instances Listener Functions */
    /**
     * Instance Manager - New Instance found
     */
    override fun onInstanceStart(instance: Instance) {
        // Get Instance Set for Instance ID, create, add and return a new one if it doesn't exist
        // > For Mini, only one will exist where Name = Title
        // > Future Versions may have more than one

        instanceManager?.let {
            synchronized(it) {
                LOGGER.trace { "onInstanceStart: Instance: $instance}" }
                // Add Instance to Map
                synchronized(instanceMap) {
                    //Add to instanceMap
                    val map = instanceMap.getOrPut(instance.id.toString()) { LinkedHashMap() }
                    map[instance.instanceConnectionID] = instance

                    if (oldestInstance == null || instance.id.timestamp < (oldestInstance?.id?.timestamp
                            ?: Long.MIN_VALUE)
                    ) {
                        // Set with this instance of oldestInstance if null or current inst is older than current
                        oldestInstance = instance
                    }
                }

                // Create Connection and add to Connection Collection
                synchronized(collInstConnections) {
                    LOGGER.trace { "onInstanceStart: Construct Connection ${instance.server} ${instance.title}" }
                    val connMap = collInstConnections.getOrPut(instance.id.toString()) { LinkedHashMap() }

                    val newConnection = instance.connect(this, "TouchPortal-${instance.id}")
                    connMap.put(newConnection.instance.title, newConnection)
                }

                updatePrimaryConnection()
            }
        }
    }


    /**
     * Instance Manager Event - Existing Instance Updated
     *
     * Usually a Name or Server IP change, requiring reconnection
     */
    override fun onInstanceChangeMajor(instance: Instance, oldInstance: Instance) {
        instanceManager?.let {
            synchronized(it) {
                if (oldInstance.server != instance.server) {
                    //More changed
                    LOGGER.debug { "onInstanceChangeMajor: run instanceConnectionCloseAndCleanup with ${oldInstance.server} ${oldInstance.title}" }
                    instanceConnectionCloseAndCleanup(oldInstance)
                    LOGGER.trace { "onInstanceChangeMajor: run OnConnect with ${instance.server} ${instance.title}" }
                    onInstanceStart(instance)
                }
                updatePrimaryConnection()
            }
        }
    }


    /**
     * Instance Manager Event - Existing Instance Updated
     *
     * A Minor change like a Window Title or Server IP change, requiring reconnection
     */
    override fun onInstanceChangeMinor(instance: Instance, change: InstanceChange, oldValue: String) {
        instanceManager?.let {
            synchronized(it) {

                when (change) {
                    InstanceChange.NAME -> {
                        //Just Name changed
                        LOGGER.debug { "onInstanceChangeMinor: Updated ${instance.server} title: '$oldValue' > '${instance.title}'" }

                        synchronized(collInstConnections) {
                            // Update Linked Hash Map - Remove Old Title Key, add connection against new key if it existed
                            val connMap = collInstConnections.getOrPut(instance.id.toString()) { LinkedHashMap() }

                            connMap.remove(oldValue)?.let { connection ->
                                connMap.put(instance.title, connection)

                            }
                        }
                    }
                }

                updatePrimaryConnection()
            }
        }
    }


    /**
     * Instance Manager Event - Existing Instance Closed
     */
    override fun onInstanceEnd(id: InstanceID) {
        instanceManager?.let { instanceManager ->
            synchronized(instanceManager) {
                LOGGER.trace { "onInstanceEnd: End $id" }

                instanceIdConnectionCloseAndCleanup(id)

                updatePrimaryConnection()
            }
        }
    }


    /**
     * Close and Cleanup all Instances/Connections linked to an InstanceID
     */
    private fun instanceConnectionCloseAndCleanup(instance: Instance) {
        LOGGER.trace { "instanceCloseAndCleanup: Close and cleanup instance ${instance.server} ${instance.title} " }

        // Remove connection from Collection and make sure connection is closed
        synchronized(collInstConnections) {

            collInstConnections[instance.id.toString()]?.get(instance.title)?.let {
                LOGGER.trace { "instanceConnectionCloseAndCleanup: Close Connection ${it.server} ${it.name}" }
                it.close()

                //Cleanup States
                cleanupConnectionStates(it)
            }
        }

        //Remove from Map
        synchronized(instanceMap) {
            LOGGER.trace { "instanceConnectionCloseAndCleanup: Remove Instance from Map ${instance.instanceConnectionID}" }
            instanceMap[instance.id.toString()]?.remove(instance.instanceConnectionID)
        }
    }


    private fun updateOldestInstance() {

        for (instMap in instanceMap.values) {
            val inst = instMap.values.first()
            if (oldestInstance == null || inst.id.timestamp < (oldestInstance?.id?.timestamp ?: Long.MIN_VALUE)) {
                // Set with this instance of oldestInstance if null or current inst is older than current
                oldestInstance = inst
            }
        }

    }


    /**
     * Close and Cleanup all Instances/Connections linked to an InstanceID
     */
    private fun instanceIdConnectionCloseAndCleanup(id: InstanceID) {
        LOGGER.trace { "instanceCloseAndCleanup: Close and cleanup instance $id " }

        // Remove connection from Collection and make sure connection is closed
        synchronized(collInstConnections) {
            collInstConnections.remove(id.toString())?.values?.forEach { connectionToEnd ->

                LOGGER.trace { "onInstanceEnd: Close Connection ${connectionToEnd.server} ${connectionToEnd.name}" }
                if (connectionToEnd == primaryConnection) {
                    // Clear Current State
                    sendStateClearCurrentAvatarState()
                    sendStateClearCurrentAvatarStateName()
                    sendStateClearCurrentAvatarStateThumbnail()
                    sendStateClearCurrentAvatarStateId()
                    sendChoiceClearCurrentAvatarState()
                }

                connectionToEnd.close()

                //Cleanup States
                cleanupConnectionStates(connectionToEnd)
            }
        }

        //Remove from Map
        synchronized(instanceMap) {
            instanceMap.remove(id.toString())

            //Check if oldest instance is Ended
            if (oldestInstance?.id == id) {
                oldestInstance = null
                //If oldest removed, try and find a replacement

                updateOldestInstance()
            }
        }
    }


    private fun cleanupConnectionStates(connection: Connection) {
        //Cleanup States
        collInstConnections[connection.instance.id.toString()]?.remove(connection.instance.title)

        collConnectionData.remove(connection)
    }


    /* Connection Listener Functions */
    override fun onConnectionError(connection: Connection, error: ConnectionError, exception: Exception?): Boolean {
        // Veadotube Connection Error
        LOGGER.trace { "onConnectionError: Connection ${connection.connUri}, Error ${error.name}" }

        // Whether the connection is told to cancel at the end
        var returnCancelConnection = false

        synchronized(collInstConnections) {

            when (error) {
                ConnectionError.FailedToConnect -> {
                    // Failed to connect
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Failed to Connect: ${exception?.message}" }
                    returnCancelConnection = true
                    connection.close()
                    instanceManager?.markInstanceFailed(connection.instance.id)
                }

                ConnectionError.ExceededRetries -> {
                    // Terminal, tell Manager to clear from known list
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Connect Retries Exceeded" }
                    returnCancelConnection = true // Ignored, terminal in constructor
                    connection.close()
                    instanceManager?.markInstanceFailed(connection.instance.id)
                }

                ConnectionError.InvalidServerOrName -> {
                    /* Terminal */
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Invalid Server Or Name" }
                    returnCancelConnection = true // Ignored in constructor
                    instanceManager?.markInstanceFailed(connection.instance.id)
                }

                ConnectionError.Unknown -> {
                    /* Log but let Connection continue */
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Error: ${exception?.message}" }
                }
            }


            if (collInstConnections[connection.instance.id.toString()]?.equals(connection) != true) {
                // If Connection is not in Collection, make sure it closes.
                // Otherwise, it will retry several times before giving up
                connection.close()
            }
        }

        return returnCancelConnection
    }


    override fun onConnectionChange(connection: Connection, active: Boolean) {
        LOGGER.trace { "onConnectionChange: Connection ${connection.connUri}, Active $active" }
        // Veadotube Connection Activated/Up or Deactivated/Down
        if (active) {
            /* Connection Marked active */

            synchronized(collInstConnections) {
                // Add to map
                val linked =
                    collInstConnections.getOrPut(connection.instance.id.toString()) { LinkedHashMap() }
                linked[connection.instance.title] = connection

                // Create ConnectionData
                collConnectionData[connection] = VeadoConnectionData(connection)

                // Request list of possible States
                sendRequestStateList(connection)

                // Request Current State
                sendRequestStatePeek(connection)

                // Start State Listener
                sendRequestStartListener(connection)
            }
        } else {
            /* Connection Marked inactive */
            synchronized(collInstConnections) {
                //Stop Listener
                sendRequestStopListener(connection)

                cleanupConnectionStates(connection)
            }
        }

    }


    override fun onConnectionReceive(connection: Connection, message: ResultMessage) {
        // Receive message from Veadotube
        LOGGER.debug { "onConnectionReceive: -> Connection ${connection.connUri} from Channel ${message.channel} received ${message.event} Message" }

        when (message) {
            is ResultMessage.ResultMessageWithInstanceInfo -> {
                LOGGER.debug { "onConnectionReceive: Instance Info" }
                LOGGER.trace { "Message -> Channel: ${message.channel}" }
                LOGGER.trace { "Message -> ID:      ${message.id}" }
                LOGGER.trace { "Message -> Name:    ${message.name}" }
                LOGGER.trace { "Message -> Server:  ${message.server}" }
                LOGGER.trace { "Message -> Version: ${message.version}" }
            }

            is ResultMessage.ResultMessageWithEntryList -> {
                // Result from request: `nodes:{"event": "list"}`
                // This returns the entries - e.g. stateEvents - avatar state.
                // These values are sent in other request types
                // Mini just uses stateEvents, so currently we just assume id = mini and type = stateEvents
                // instead of requesting them first but this might change with other versions (Full, etc.)

                LOGGER.debug { "onConnectionReceive: Message List -> Entry List (${message.entries.count()} Items)" }

                for (entry in message.entries) {
                    LOGGER.trace { "onConnectionReceive: Message -> Entry > Type: ${entry.type}; ID: ${entry.id}; Name: ${entry.name}" }
                }
            }

            is ResultMessage.ResultMessageWithPayload -> {
                LOGGER.debug { "onConnectionReceive: Message Payload" }
                LOGGER.trace { "Message -> ID:   ${message.id}" }
                LOGGER.trace { "Message -> Type: ${message.type}" }
                LOGGER.trace { "Message -> Name: ${message.name}" }

                when (val payload = message.payload) {
                    is BleatkanStatePeek -> {
                        // Peek result - could be Peek Request, Listener, etc.
                        LOGGER.debug { "onConnectionReceive: Message Payload -> Peek (${payload.state})" }
                        processReceivedPayloadPeek(connection, payload)
                    }

                    is BleatkanStateList -> {
                        // List of States - Received in order that they appear in Program
                        LOGGER.debug { "onConnectionReceive: Message Payload -> State List (${payload.states.count()} Items)" }
                        processReceivedPayloadAvatarStateList(connection, payload)
                    }

                    is BleatkanStateThumbnail -> {
                        // Thumb result - thumbnail for an Avatar State
                        LOGGER.debug { "onConnectionReceive: Message Payload -> Thumbnail" }
                        processReceivedPayloadThumbnail(connection, payload)
                    }
                }
            }

        }
    }


    /**
     * Veadotube Connection Update - Message Received
     *
     * @param connection Connection providing update
     * @param payload State List Data Received
     */
    private fun processReceivedPayloadAvatarStateList(
        connection: Connection,
        payload: BleatkanStateList
    ) {
        LOGGER.debug { "processReceivedPayloadAvatarStateList: Update Collection Maps" }
        synchronized(connection) {
            // Add/Replace existing Lists/Maps
            collConnectionData[connection]?.updateStates(payload)

            onUpdateAvatarStateList(connection)
        }
    }


    /**
     * Call when Peek Message Received - updates State ID/Name, etc. and sends to Touch Portal
     *
     * We may not have the state name yet - if not, a State Request should be sent
     *
     * @param connection Connection providing update
     * @param payload State Peek Data Received
     */
    private fun processReceivedPayloadPeek(
        connection: Connection,
        payload: BleatkanStatePeek
    ) {
        LOGGER.trace { "Message -> Payload -> Event: ${payload.event}, State: ${payload.state}" }

        synchronized(connection) {
            // Update Current State
            val connData = collConnectionData[connection]

            if (connData != null) {

                //Update value, return if it nothing is updated (false) - possible if Peek requests are sent
                if (!connData.updateCurrentState(payload)) return

                val stateCurrent = connData.currentState

                sendStateUpdateCurrentAvatarStateId(payload.state)

                if (stateCurrent != null) {
                    //If we have the name, update to Touch Portal
                    sendStateUpdateCurrentAvatarState(connection, stateCurrent)

                    //Name value
                    val stateCurrentName = stateCurrent.name
                    if (stateCurrentName.isNullOrEmpty()) {
                        //If we don't have the name, send request for fresh state list
                        sendRequestStateList(connection)
                    } else {
                        try {
                            sendStateUpdateCurrentAvatarStateName(stateCurrentName)
                        } catch (_: Exception) {/* Do nothing */
                        }
                    }

                    if (settingVeadoAutoRequestThumbnailEnabled) {
                        when (val png = stateCurrent.thumbnail?.png) {
                            null -> sendRequestStateThumbnail(connection, stateCurrent.id)
                            else -> sendStateUpdateCurrentAvatarStateThumbnail(png)
                        }
                    }
                }

            } else {
                LOGGER.debug { "updateCurrentAvatarStateId: couldn't find collConnectionData for ${connection.connUri}" }
            }
        }
    }


    /**
     * Call when Current State has updated - updates name and sends to Touch Portal
     *
     * e.g. State Names may have Changed, etc.
     *
     * Probably obsolete
     */
    @Deprecated("Obsolete")
    private fun onCurrentStateNameUpdated(connection: Connection) {
        // Update current state name
        synchronized(connection) {

            //Get current State for Connection
            val currentState = collConnectionData[connection]?.currentState
            LOGGER.debug { "updateCurrentStateName: Got Current State $currentState" }

            if (currentState != null) {
                //If not null, send

                sendStateUpdateCurrentAvatarState(connection, currentState)

                sendStateUpdateCurrentAvatarStateName(currentState.name ?: "Unknown")

            }
        }
    }


    private fun processReceivedPayloadThumbnail(connection: Connection, payload: BleatkanStateThumbnail) {
        LOGGER.trace { "Message -> Payload -> Event/State:  ${payload.event}; ${payload.state}" }
        LOGGER.trace { "Message -> Payload -> Height/Width: ${payload.height}/${payload.width}" }
        LOGGER.trace { "Message -> Payload -> PNG B64 Chars: ${payload.png.count()}" }


        val collData = collConnectionData[connection] ?: return

        // Update Thumbnail - May need to process image to make it square
        val updated: Boolean = collData.updateStateThumbnail(payload)

        collData.currentState.let { currState ->

            if (currState?.id == payload.state) {

                currState.thumbnail?.png?.let { png ->
                    if (updated || stateCurrentAvatarStateThumbnail != png) {
                        // If matches current state, update Touch Portal
                        sendStateUpdateCurrentAvatarStateThumbnail(png)
                    }
                }
            }
        }
    }


    /**
     * Token for Listener
     */
    private val listenerToken = "TpVtPlugin.ChangeState"

    /**
     * Nodes Channel - default channel used in Mini
     */
    private val channelNodes = "nodes"

    /**
     * Instance Channel - channel used to get Instance Info similar to Instance File
     */
    private val channelInstance = "instance"


    /**
     * Actions for updating the Current Avatar State in Touch Portal etc.
     *
     * State and State Name, etc
     *
     * @see stateCurrentAvatarState
     */
    @Suppress("DEPRECATION")
    private fun sendStateUpdateCurrentAvatarState(
        connection: Connection,
        state: VtState,
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        // State ID is different pre 2.1 - from 2.1 it's just the name
        val stateString = if (connection.compatibilityFlagMiniPre2dot1) {
            // Generate String with Name and ID - pre 2.1
            avatarStateToString(state.id, state.name ?: "Unknown")
        } else {
            // ID is just name
            state.id
        }
        stateCurrentAvatarState = stateString

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarState.ID,
            stateString,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )

    }


    /**
     * Action for clearing the Current Avatar State in Touch Portal etc.
     *
     * State and State Name, etc
     *
     * @see stateCurrentAvatarState
     */
    private fun sendStateClearCurrentAvatarState() {
        stateCurrentAvatarState = ""

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarState.ID,
            stateCurrentAvatarState,
        )

    }


    /**
     * Actions for updating the Current Avatar State ID in Touch Portal etc.
     *
     * State ID Only
     *
     * @see stateCurrentAvatarStateId
     */
    private fun sendStateUpdateCurrentAvatarStateId(
        stateID: String,
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        stateCurrentAvatarStateId = stateID

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateId.ID,
            /* value = */ stateCurrentAvatarStateId,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )

    }


    /**
     * Actions for clearing the Current Avatar State ID in Touch Portal etc.
     *
     * State ID Only
     *
     * @see stateCurrentAvatarStateId
     */
    private fun sendStateClearCurrentAvatarStateId() {
        stateCurrentAvatarStateId = ""

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateId.ID,
            /* value = */ stateCurrentAvatarStateId,
            /* allowEmptyValue = */ true,
            /* forceUpdate = */ false
        )

    }


    /**
     * Actions for updating the Current Avatar State Name in Touch Portal etc.
     *
     * State Name Only
     *
     * @see stateCurrentAvatarStateName
     */
    private fun sendStateUpdateCurrentAvatarStateName(
        stateName: String,
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        stateCurrentAvatarStateName = stateName

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateName.ID,
            /* value = */ stateCurrentAvatarStateName,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )

    }


    private fun sendStateClearCurrentAvatarStateName() {
        stateCurrentAvatarStateName = ""

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateName.ID,
            /* value = */ stateCurrentAvatarStateName,
            /* allowEmptyValue = */ true,
            /* forceUpdate = */ false
        )
    }


    /**
     * Actions for updating the Current Avatar State Thumbnail in Touch Portal etc.
     *
     * State Thumbnail Only
     *
     * @see stateCurrentAvatarStateName
     */
    private fun sendStateUpdateCurrentAvatarStateThumbnail(
        stateThumbnail: String,
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        stateCurrentAvatarStateThumbnail = stateThumbnail

        // Update State
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateThumbnail.ID,
            /* value = */ stateCurrentAvatarStateThumbnail,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )
    }


    /**
     * Actions for updating the Current Avatar State Thumbnail in Touch Portal etc.
     *
     * State Thumbnail Only
     *
     * @see stateCurrentAvatarStateName
     */
    private fun sendStateClearCurrentAvatarStateThumbnail() {
        stateCurrentAvatarStateThumbnail = ""

        // Update State
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateThumbnail.ID,
            /* value = */ stateCurrentAvatarStateThumbnail,
            /* allowEmptyValue = */ true,
            /* forceUpdate = */ false
        )
    }


    /**
     * Actions for updating the Choices for [actionSetAvatarStateFromList] and [stateCurrentAvatarState] in Touch Portal
     *
     * @see actionSetAvatarStateFromList
     */
    private fun sendChoiceUpdateCurrentAvatarState(choices: ArrayList<String>) {
        LOGGER.trace { "sendChoiceUpdateCurrentAvatarState: Sending choices: $choices" }

        // Update State Choices
        val toTypedArray = choices.toTypedArray()

        this.sendChoiceUpdate(
            VeadoTouchPluginConstants.PrimaryInstance.Actions.SetAvatarStateFromList.Choices.ID,
            toTypedArray
        )
        //        //Disabled, Event removed for now
        //        this.sendChoiceUpdate(
        //            VeadoTouchPluginConstants.PrimaryInstance.Events.CurrentAvatarState.ID,
        //            toTypedArray
        //        )
    }


    /**
     * Actions for updating the Choices for [actionSetAvatarStateFromList] and [stateCurrentAvatarState] in Touch Portal
     *
     * @see actionSetAvatarStateFromList
     */
    private fun sendChoiceClearCurrentAvatarState() {
        LOGGER.trace { "sendChoiceUpdateCurrentAvatarState: Clearing Choices" }

        // Clear State Choices
        val toTypedArray = Array(1) { "" }

        this.sendChoiceUpdate(
            /* listId = */ VeadoTouchPluginConstants.PrimaryInstance.Actions.SetAvatarStateFromList.Choices.ID,
            /* values = */ toTypedArray,
            /* allowEmptyArrayValues = */ true
        )

        //        //Disabled, Event removed for now
        //        this.sendChoiceUpdate(
        //            /* listId = */ VeadoTouchPluginConstants.PrimaryInstance.Events.CurrentAvatarState.ID,
        //            /* values = */ toTypedArray,
        //            /* allowEmptyArrayValues = */ true
        //        )
    }


    /* Veado Requests */
    private fun sendRequestInstanceInfo(connection: Connection) {
        try {
            connection.send(
                channel = channelInstance,
                requestData = VeadoRequest.getEventInfo
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Instance Info for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestStateList(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                requestData = VeadoRequest.getListStateMini
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request State List for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestStatePeek(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                requestData = VeadoRequest.getPeekStateMini
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Current State for ${connection.connUri}: ${ex.message}" }
        }
    }

    /**
     * Send request for Push-To-Talk Mic Input
     *
     * Warning:
     * * Enabling Push-to-Talk 'Mutes' the Microphone input
     * until an API message to toggle/unmute is sent
     * * If a hotkey is set, API won't work
     *
     *
     * @param sendValue
     * * true > PPT Node 'enabled' > Mic Unmuted
     * * false > PPT Node 'disabled' > Mic Muted
     * * null > Toggle
     *
     *
     */
    private fun sendRequestPushToTalkMicInput(connection: Connection, sendValue: Boolean? = null) {
        //TODO Create proper Bleatkan Request Message for PPT
        try {
            val pushToTalk =
                "{\"event\":\"payload\",\"type\":\"boolean\",\"id\":\"mini\",\"payload\": {${
                    if (sendValue != null)
                        "\"event\":\"set\",\"value\":$sendValue"
                    else "\"event\":\"toggle\""
                }}}"
            LOGGER.trace { "sendRequestPushToTalkMicInput: $pushToTalk" }
            connection.send(
                channel = channelNodes,
                requestData = pushToTalk
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Set Push To Talk for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestStateThumbnail(connection: Connection, stateID: String) {
        try {
            connection.send(
                channel = channelNodes,
                requestData = VeadoRequest.createThumbnailStateMini(stateID)
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Current State Thumbnail for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestStartListener(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                VeadoRequest.createListenStateMini(listenerToken)
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Listener Start for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestStopListener(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                VeadoRequest.createUnlistenStateMini(listenerToken)
            )
        } catch (ex: Exception) {
            LOGGER.debug { "Failed to Request Listener Stop for ${connection.connUri}: ${ex.message}" }
        }
    }

}


