package io.github.dissonantau.veadotubetouchportalplugin

import com.christophecvb.touchportal.TouchPortalPlugin
import com.christophecvb.touchportal.annotations.*
import com.christophecvb.touchportal.annotations.State
import com.christophecvb.touchportal.helpers.PluginHelper
import com.christophecvb.touchportal.model.*
import com.google.gson.JsonObject
import io.github.dissonantau.bleatkan.connection.Connection
import io.github.dissonantau.bleatkan.connection.ConnectionError
import io.github.dissonantau.bleatkan.connection.ConnectionListener
import io.github.dissonantau.bleatkan.instance.*
import io.github.dissonantau.bleatkan.message.*
import io.github.dissonantau.bleatkan.message.RequestMessage.RequestMessageNodeEvent
import io.github.dissonantau.bleatkan.message.VeadoRequest.FACTORY.getPayloadEventGet
import io.github.dissonantau.bleatkan.message.VeadoRequest.FACTORY.getPayloadEventList
import io.github.dissonantau.veadotubetouchportalplugin.data.VeadoInstanceMap
import io.github.dissonantau.veadotubetouchportalplugin.data.VtState
import io.github.dissonantau.veadotubetouchportalplugin.notification.NotificationHelper
import io.github.dissonantau.veadotubetouchportalplugin.updatechecker.PluginUpdateChecker
import io.github.dissonantau.veadotubetouchportalplugin.updatechecker.ReleaseData
import io.github.dissonantau.veadotubetouchportalplugin.updatechecker.UpdateCheckResultListener
import io.github.dissonantau.veadotubetouchportalplugin.updatechecker.UpdateReleaseData
import io.github.oshai.kotlinlogging.KotlinLogging
import org.apache.commons.lang3.SystemUtils
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.locks.ReentrantLock
import kotlin.concurrent.withLock
import io.github.dissonantau.bleatkan.message.ResultPayload.ResultPayloadPng as BleatkanStateThumbnail
import io.github.dissonantau.bleatkan.message.ResultPayload.ResultPayloadState as BleatkanStatePeek
import io.github.dissonantau.bleatkan.message.ResultPayload.ResultPayloadStateList as BleatkanStateList


@Suppress("unused")
@Plugin(
    name = BuildConfig.NAME_SHORT, version = BuildConfig.VERSION_CODE,
    colorDark = "#5c1c1c", colorLight = "#822727"
)
class VeadoTouchPlugin(parallelizeActions: Boolean) :
    TouchPortalPlugin(parallelizeActions), TouchPortalPlugin.TouchPortalPluginListener,
    InstancesListener, ConnectionListener, UpdateCheckResultListener {


    companion object {
        /** Class Logger */
        @JvmStatic
        private val LOGGER =
            KotlinLogging.logger { TouchPortalPlugin::class.java.name }

        /**
         * Avatar State String RegEx
         *
         * Strings generated by [onUpdateAvatarStateList] are formatted "name (id)" and sent to Touch Portal
         *
         * This RegEx will extract the Name and ID to named groups, with space between Name and ID, and extra brackets excluded
         */
        @JvmStatic
        private val avatarStateRegex = """(?<name>.*?)?\s*\((?<id>\w+)\)""".toRegex()


        /**
         * Avatar State String RegEx
         *
         * Strings generated by [onUpdateAvatarStateList] are formatted "name (id)" and sent to Touch Portal
         *
         * This RegEx will extract the Name and ID to named groups, with space between Name and ID, and extra brackets excluded
         *
         * This Version can Handle Pre- and Post-2.1 Strings, where the ID now = Name
         *
         * It's only used for Deprecated ID Actions, as new 'By Name' Should expect Name only
         */
        @JvmStatic
        private val avatarStateRegexAny = """(?<name>.*?)? ?(?:\((?<id>.*)\))?""".toRegex()

        /** Veadotube Plugin Object */
        @JvmStatic
        private lateinit var veadotubePlugin: VeadoTouchPlugin

        /** Set Enabled when shutting down to prevent doubling up */
        @JvmStatic
        private var pluginClosing = AtomicBoolean(false)

        @JvmStatic
        fun main(args: Array<String>) {
            LOGGER.debug { "${BuildConfig.NAME} Launched with ${args.size} args: ${args.toList()}" }

            LOGGER.debug { "OS Name    : ${SystemUtils.OS_NAME ?: "Unable to get"}" }
            LOGGER.debug { "OS Version : ${SystemUtils.OS_VERSION ?: "Unable to get"}" }
            LOGGER.debug { "OS Arch    : ${SystemUtils.OS_ARCH ?: "Unable to get"}" }

            LOGGER.debug { "Kotlin Version            : ${KotlinVersion.CURRENT} " }
            LOGGER.debug { "Java Version              : ${SystemUtils.JAVA_VERSION} " }
            LOGGER.debug { "Java VM Version           : ${SystemUtils.JAVA_VM_VERSION} " }
            LOGGER.debug { "Java VM Vendor            : ${SystemUtils.JAVA_VM_VENDOR}  " }
            LOGGER.debug { "Java VM Name              : ${SystemUtils.JAVA_VM_NAME} " }
            LOGGER.debug { "Java VM Spec Version      : ${SystemUtils.JAVA_VM_SPECIFICATION_VERSION}" }
            LOGGER.debug { "Java VM Spec Vendor       : ${SystemUtils.JAVA_VM_SPECIFICATION_VENDOR}" }
            LOGGER.debug { "Java VM Spec Name         : ${SystemUtils.JAVA_VM_SPECIFICATION_NAME}" }
            LOGGER.debug { "Java Runtime Spec Version : ${SystemUtils.JAVA_SPECIFICATION_VERSION}" }
            LOGGER.debug { "Java Runtime Spec Vendor  : ${SystemUtils.JAVA_SPECIFICATION_VENDOR}" }
            LOGGER.debug { "Java Runtime Spec Name    : ${SystemUtils.JAVA_SPECIFICATION_NAME}" }

            if (args.size == 1) {

                if (PluginHelper.COMMAND_START == args[0]) {
                    LOGGER.info {
                        "${BuildConfig.NAME_SHORT} Starting - Plugin Version: ${
                            BuildConfig.VERSION_NAME_FULL
                        } - Java Version ${System.getProperty("java.version")}"
                    }

                    veadotubePlugin = VeadoTouchPlugin(true)

                    setUpShutdownHook()

                    // Initialize the Plugin
                    veadotubePlugin.initializePlugin()

                }

            }

        }

        @JvmStatic
        private fun setUpShutdownHook() {
            Runtime.getRuntime().addShutdownHook(object : Thread() {
                override fun run() {
                    LOGGER.info { "Plugin Shutting Down" }
                    // Start Shutdown
                    veadotubePlugin.shutdown()
                }
            })

        }


    }


    private fun initializePlugin() {
        LOGGER.trace { "initializePlugin: Start" }

        // Initiate the connection with the Touch Portal Plugin System
        val connectedPairedAndListening = connectThenPairAndListen(this)


        if (connectedPairedAndListening) {
            LOGGER.info { "Plugin with ID[${VeadoTouchPluginConstants.ID}] Connected and Paired!" }

        } else {
            LOGGER.error { "Failed to Connect and Pair with Touch Portal" }
            throw IllegalStateException("Failed to Connect and Pair with Touch Portal")
        }

        LOGGER.trace { "initializePlugin: Done" }
    }


    /* Touch Portal Categories */

    @Suppress("unused")
    enum class Categories {
        @Category(
            name = "Veadotube Mini - Primary Instance",
            imagePath = "images/icon-24.png"
        )
        PrimaryInstance

    }


    /* Touch Portal Settings Panel */
    /**
     * Setting - Show # of connected instances
     */
    @Setting(name = "# of Connected Instances", defaultValue = "0", isReadOnly = true)
    private var settingVeadoInstanceCount: String = "0"

    /**
     * Setting - Show Primary Instance Address
     */
    @Setting(name = "Primary Instance Address", defaultValue = "Plugin Starting", isReadOnly = true)
    private var settingVeadoPrimaryInstanceServer: String = "Plugin Starting"

    /**
     * Setting - Show Primary Instance Name
     */
    @Setting(name = "Primary Instance Name", defaultValue = "Plugin Starting", isReadOnly = true)
    private var settingVeadoPrimaryInstanceName: String = "Plugin Starting"

    /**
     * Setting - Primary Instance Name Overwrite
     */
    @Setting(name = "Mini Primary Instance Name Override (Leave Blank to Disable)", defaultValue = "")
    private var settingVeadoPrimaryInstanceNameOverride: String = ""

    /**
     * Setting - Primary Instance Name Overwrite Existing Value
     *
     * Need to use this to know what the old/existing value is due to TP SDK replacing the setting automatically,
     * bypassing Kotlin Set and not allowing a comparison of old vs new
     */
    private var settingVeadoPrimaryInstanceNameOverrideExisting: String = ""

    /**
     * Setting - Auto Request Current State Thumbnail
     *
     * Enabled/Disabled (Currently Text due to v6 API - switch to Switch in v10)
     */
    @Setting(name = "Auto Request Current State Thumbnail (Enabled/Disabled)", defaultValue = "disabled")
    private var settingVeadoAutoRequestThumbnail: String = "disabled"


    /**
     * Setting - Auto Request Current State Thumbnail Existing Value
     *
     * Enabled/Disabled (Currently Text due to v6 API - switch to Switch in v10)
     */
    private var settingVeadoAutoRequestThumbnailExisting: String = "disabled"

    /**
     * Setting - Auto Request Current State Thumbnail
     *
     * Enabled/Disabled (Currently Text due to v6 API - switch to Switch in v10)
     */
    private var settingVeadoAutoRequestThumbnailEnabled = false


    /* Touch Portal States, Events, etc. */
//    /**
//     * Current Avatar State - `Name` (`ID`) Format
//     */
//    @State(
//        desc = "Current Mini Avatar State - Name & ID (Deprecated)",
//        defaultValue = "Not Connected",
//        categoryId = "PrimaryInstance",
//        id = "currentAvatarState"
//    )
//    private var stateCurrentAvatarState: String = "Not Connected"
// TODO Remove

//    /**
//     * Current Avatar State ID
//     */
//    @State(
//        desc = "Current Mini Avatar State - ID (Deprecated)",
//        defaultValue = "Not Connected",
//        categoryId = "PrimaryInstance",
//        id = "currentAvatarStateId"
//    )
//    private var stateCurrentAvatarStateId: String = "Not Connected"
// TODO Remove

    /**
     * Current Avatar State - Name
     */
    @State(
        desc = "Current Mini Avatar State - Name",
        defaultValue = "Not Connected",
        categoryId = "PrimaryInstance",
        id = "currentAvatarStateName"
    )
    private var statePrimaryMiniCurrentAvatarStateName: String = "Not Connected"
    //TODO Prev PrimaryInstance ; currentAvatarStateName

    /**
     * Current Avatar State - Thumbnail
     */
    @State(
        desc = "Current Mini Avatar State - Thumbnail",
        defaultValue = "",
        categoryId = "PrimaryInstance",
        id = "currentAvatarStateThumbnail"
    )
    private var statePrimaryMiniCurrentAvatarStateThumbnail: String = ""
    //TODO Prev PrimaryInstance ; currentAvatarStateThumbnail

    /**
     * Set Current Avatar State with State ID String in 'Name (ID)' Format (Mini 2.0) or just Name (Mini 2.1+)
     */
    @Action(
        name = "Set Mini Avatar State from List",
        format = "Set Mini Avatar State to {\$choices\$}",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setAvatarStateFromList"
    )
    private fun actionSetAvatarStateFromList(@Data(valueChoices = [""]) choices: Array<String>) {
        val connection = primaryMiniConnection
        if (connection != null) {
            //Get State Object ID from String
            try {
                val newState = findAvatarFromStateString(connection, choices[0])

                if (newState != null) {
                    connection.send(channelNodes, VeadoRequest.createSetStateMini(newState.id))
                    LOGGER.debug {
                        "actionSetAvatarStateFromList: Set to '${choices[0]}'"
                    }
                } else {
                    LOGGER.warn { "Avatar Choice not Found: ${choices[0]}" }
                }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to send Set Avatar State From List: ${ex.message}" }
            }
        } else {
            LOGGER.warn { "Set Mini Avatar State from List: No connection, can't set Set Avatar to '${choices[0]}'" }
        }
    }


    /**
     * Set Current Avatar State by Name
     *
     * Message from
     */
    @Action(
        name = "Set Mini Avatar State by Name",
        format = "Set Mini Avatar to State with Name {\$text\$}",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setAvatarStateByName"
    )
    private fun actionSetAvatarStateByName(@Data text: String) {
        //TODO
        val connection = primaryMiniConnection
        if (connection != null) {
            val stateChange =
                if (connection.compatibilityFlagMiniPre2dot1) {
                    // Get connection states, find name
                    veadoInstanceMaps.getConnectionData(connection)?.getStateByNameContains(text)?.name
                } else {
                    text.trim()
                }

            if (stateChange == null) {
                LOGGER.warn { "Set Avatar State by Name: Can't find Name match for '$text'" }
                return
            }
            try {
                connection.send(channelNodes, VeadoRequest.createSetStateMini(stateChange))
                LOGGER.debug { "actionSetAvatarStateByName: Set ${connection.server} Avatar to '$text'" }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to send Set Avatar State By Name for ${connection.connUri}: ${ex.message}" }
            }
            return
        } else {
            LOGGER.warn { "Set Mini Avatar State by Name: No connection, can't set Set Avatar to '$text'" }
        }
    }


    /**
     * Set Current Avatar State ID
     *
     * Deprecated from Mini 2.1
     */
    @Action(
        name = "Set Avatar State by ID (Mini 2.0)",
        format = "Set Avatar to State with ID {\$text\$} (Deprecated from Mini 2.1)",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setAvatarStateByID"
    )
    private fun actionSetAvatarStateByID(@Data text: String) {
        val connection = primaryMiniConnection
        if (connection != null) {
            try {
                connection.send(channelNodes, VeadoRequest.createSetStateMini(text.trim()))
                LOGGER.debug { "actionSetAvatarStateByID: Set ${connection.server} Avatar to $text" }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to send Set Avatar State By ID for ${connection.connUri}: ${ex.message}" }
            }
        } else {
            LOGGER.warn { "Set Avatar State by ID: No connection, can't set Set Avatar to '$text'" }
        }
    }


    /**
     * Set Push To Talk/Mute input
     *
     * Enabling Push to Talk Mutes until the PTT Hotkey is pressed
     *
     */
    @Action(
        name = "Push-to-Talk Mic Input",
        format = "{\$choices\$} veadotube Push-to-Talk Microphone Input",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "setPushToTalkMicInput"
    )
    private fun actionSetPushToTalkMicInput(@Data(valueChoices = ["Toggle", "Unmute", "Mute"]) choices: Array<String>) {
        LOGGER.debug { "actionSetPushToTalkMicInput: Set to '${choices[0]}'" }
        val connection = primaryMiniConnection
        if (connection != null) {
            try {
                when (choices[0]) {
                    "Toggle" -> sendRequestMiniPushToTalkMicInput(connection, null)
                    "Unmute" -> sendRequestMiniPushToTalkMicInput(connection, true) // Prev Enable
                    "Mute" -> sendRequestMiniPushToTalkMicInput(connection, false) // Prev Disable
                }
            } catch (ex: Exception) {
                LOGGER.debug { "actionSetPushToTalkMicInput: Error sending message ${ex.message}" }
            }

        }
    }


    /**
     * Send Custom JSON Request
     *
     */
    @Action(
        name = "Send Custom JSON Request",
        format = "Send JSON Request to Primary Instance - Channel:{\$channel\$}\nJSON:{\$json\$}",
        categoryId = "PrimaryInstance",
        prefix = "Veadotube Mini",
        id = "actionSendCustomJsonRequest"
    )
    private fun actionSendCustomJsonRequest(@Data channel: String, @Data json: String) {
        val connection = primaryMiniConnection
        if (connection != null) {
            try {
                connection.send(channel, json)
                LOGGER.debug { "actionSendCustomJsonRequest: Sent ${connection.server} message: '$channel:$json'" }
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to Send Custom JSON Request '$channel:$json' for ${connection.connUri}: ${ex.message}" }
            }
        } else {
            LOGGER.warn { "Send Custom JSON Request: No connection, can't send message: '$channel:$json'" }
        }
    }


    /* Main Vars */
    /**
     * Veadotube Instance Manager
     *
     * Reads Veadotube Instance Directory,
     *  alerts supplied [InstancesListener] (this) of changes
     */
    private var instanceManager: InstancesManager? = null

    /**
     * Map of Veado Instances, Collections, and data
     *
     */
    private val veadoInstanceMaps = VeadoInstanceMap()

    /**
     * Lock for work related to veadoInstanceMaps
     */
    private val veadoInstanceMapsLock = ReentrantLock()

    ///**
    // * Map of Veado Types (Full, Mini) and List with InstanceID
    // *
    // * String = Full/Mini
    // *
    // * String = [InstanceID.toString] Value
    // *
    // */
    //private val instanceTypeMaps =
    //    HashMap<String, LinkedHashMap<String, Instance>>()

    ///**
    // * Veadotube Instance Collection
    // *
    // * String = [InstanceID.toString] Value
    // *
    // * Instance = Map of [Instance.instanceConnectionID] vs Instance Objects
    // *
    // * Should be run in a Synchronized context
    // */
    //private val instanceMap =
    //    HashMap<String, LinkedHashMap<String, Instance>>()

    ///**
    // * Veadotube Connection Collection
    // *
    // * String - [InstanceID.toString] Value
    // *
    // * Connection - Connection Map [Connection].[Instance.title] vs [Connection]
    // *
    // * Should be run in a Synchronized context
    // */
    //private val collInstConnections =
    //    HashMap<String, LinkedHashMap<String, Connection>>()

    ///**
    // * Map of [Connection]s with related [VeadoConnectionData]
    // *
    // * Contains data collected from Connection
    // *
    // * Work on held objects with should be synchronized with the [Connection] to prevent issues.
    // *
    // */
    //private val collConnectionData =
    //    HashMap<Connection, VeadoConnectionData>()

    ///**
    // * Veadotube Instance Collection
    // *
    // * String = [InstanceID.toString] Value
    // *
    // * String = [Connection].[Instance.title] Value
    // *
    // * Should be run in a Synchronized context
    // */
    //private val collInstanceIDTitle = TreeBidiMap<String, String>()


    /**
     * Oldest instance by Launch time
     *
     * Used to work out Primary Connection
     */
    private var oldestMiniInstance: Instance? = null

    /**
     * Primary Connection
     *
     * Used for actions etc. that don't specify a Connection
     *
     * Is Connection of Oldest Instance by default, or a match
     */
    private var primaryMiniConnection: Connection? = null


    /**
     * Creates an Avatar State String from a State
     *
     * In the format of "`name` (`id`)"
     *
     * Note: Not needed 2.1 and later
     *
     * @param state State to Generate String from
     */
    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("2.1 removes separate ID")
    private fun avatarStateToString(state: VtState) =
        "${state.name} (${state.id})"


    /**
     * Creates an Avatar State String from a State Name and ID
     *
     * In the format of "`name` (`id`)"
     *
     * Note: Not needed 2.1 and later
     *
     * @param stateId ID to Generate String from
     * @param stateName Name to Generate String from
     */
    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("2.1 removes separate ID")
    private fun avatarStateToString(stateId: String, stateName: String) =
        "$stateName ($stateId)"


    /**
     * Updates the Avatar States for a Connection/Veadotube Instance in
     *
     * @param connection Connection where List was updated
     */
    @Suppress("DEPRECATION")
    private fun onUpdateAvatarStateList(connection: Connection) {
        val choices: ArrayList<String> = ArrayList()
        val choicesId: ArrayList<String> = ArrayList()

        /* primary Instance Choices*/
        // Oldest ID is primary
        val oldestInstanceID: InstanceID? = oldestMiniInstance?.id

        val collectionsStates: ArrayList<VtState>? =
            veadoInstanceMaps.getConnectionData(connection)?.statesAll

        if (!collectionsStates.isNullOrEmpty()) {
            for (state in collectionsStates) {

                val stateString = if (connection.compatibilityFlagMiniPre2dot1) {
                    // Generate String with Name and ID - pre 2.1
                    avatarStateToString(state)
                } else {
                    // ID is just name
                    state.id
                }

                LOGGER.trace { "updateAvatarState: Added Choice \"$stateString\"" }
                choices.add(stateString)
                choicesId.add(state.id)
            }
        }


        if (oldestInstanceID == connection.instance.id) {
            // Update State Choice for primary State Chooser
            sendChoiceUpdateCurrentAvatarState(choices)
        }

    }


    /** Dynamic State - Updated
     *
     * May be removed
     */
    private fun triggerAvatarUpdatedEvent(
        state: String = "Unknown",
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        this.sendCreateState(
            /* categoryId = */ "CategoryVeadotube",
            /* stateId = */ "avatarStateUpdated",
            /* parentGroup = */ "Veadotube",
            /* description = */ "Avatar State Updated",
            /* value = */ state,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )
    }


    /**
     * Extracts the ID from an Avatar State String and returns the matched Avatar State
     *
     * Returns a [VtState] if a match is found, `null` if not
     */
    private fun findAvatarFromStateString(connection: Connection, avatarStateString: String): VtState? {
        // Default Format is "<Name> (<ID>)" where ID is the State ID

        // State ID is different pre 2.1 - from 2.1 it's just the name
        val stateID = if (connection.compatibilityFlagMiniPre2dot1) {
            // Extract ID - pre 2.1
            findAvatarIDFromStatusString(avatarStateString) ?: return null
        } else {
            // ID is just name
            avatarStateString.trim()
        }

        val matchedState = veadoInstanceMaps.getConnectionData(connection)?.getStateByID(stateID)

        LOGGER.debug {
            if (matchedState != null) {
                "findAvatarFromStateString: State Matched -> '${matchedState.id}', '${matchedState.name}'"
            } else {
                "findAvatarFromStateString: State '$stateID' not matched"
            }
        }

        return matchedState
    }


    /**
     * Extracts the ID from an Avatar State String and returns value
     *
     * Returns the Extracted ID if a match is found, `null` if not
     */
    private fun findAvatarIDFromStatusString(avatarStateString: String): String? {
        // Default Format is "<Name> (<ID>)" where ID is the State ID

        val matches = avatarStateRegex.find(avatarStateString)

        if (matches == null)
            LOGGER.warn { "findAvatarIDFromStatusString: Invalid Avatar State String: '$avatarStateString'" }
        else
            LOGGER.debug { "findAvatarIDFromStatusString: Regex found -> Name='${matches.groups["name"]?.value}' ID='${matches.groups["id"]?.value}'" }

        return matches?.groups?.get("id")?.value
    }


    /* Actions */
    @Action(name = "Refresh Avatar State List", categoryId = "PrimaryInstance", prefix = "Veadotube Mini")
    fun refreshStateListAll() {
        //TODO Make more Versions?
        LOGGER.info { "refreshStateListAll" }

        veadoInstanceMaps.getConnectionsList()

        //request update from all channels
        veadoInstanceMaps.getConnectionsList().forEach {
            try {
                it.send(channel = channelNodes, VeadoRequest.getListStateMini)
                it.send(channel = channelNodes, VeadoRequest.getPeekStateMini)
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to Refresh Avatar State List for ${it.connUri}: ${ex.message}" }
            }
        }
    }


    @Action(name = "Refresh Current Avatar State", categoryId = "PrimaryInstance", prefix = "Veadotube Mini")
    fun getAvatarStateAll() {
        //TODO Make more Versions?
        LOGGER.info { "getAvatarStateAll triggered" }

        //request update from all channels
        veadoInstanceMaps.getConnectionsList().forEach {
            LOGGER.debug { "getAvatarStateAll: send request triggered - channel $channelNodes; request ${VeadoRequest.getPeekStateMini}" }
            try {
                it.send(channel = channelNodes, VeadoRequest.getPeekStateMini)
            } catch (ex: Exception) {
                LOGGER.warn { "Failed to Refresh Current Avatar State for ${it.connUri}: ${ex.message}" }
            }
        }
    }


    /**
     * Carries out shutdown, makes sure everything closes gracefully
     */
    private fun shutdown() {
        if (pluginClosing.getAndSet(true)) {
            return
        }

        runCatching { instanceManager?.close() }
        runCatching { Connection.closeAll() }

        if (veadotubePlugin.isConnected) {
            veadotubePlugin.close(null)
        }
    }


    /* Call Backs */
    override fun onDisconnected(exception: Exception?) {
        LOGGER.trace {
            when (exception) {
                null ->
                    "onDisconnected received"

                else ->
                    "onDisconnected received - exception: $exception"
            }
        }

    }


    override fun onReceived(jsonMessage: JsonObject) {
        // For unmapped actions, etc.
        LOGGER.debug { "onReceived - unexpected: $jsonMessage." }
    }


    override fun onListChanged(tpListChangeMessage: TPListChangeMessage) {
        LOGGER.debug { "onListChanged - unexpected: ${tpListChangeMessage.listId};${tpListChangeMessage.instanceId};${tpListChangeMessage.actionId};${tpListChangeMessage.value};" }
    }


    override fun onInfo(tpInfoMessage: TPInfoMessage) {
        LOGGER.debug { "onInfo ${tpInfoMessage.status}; ${tpInfoMessage.settings}" }

        if (tpInfoMessage.status == "paired") {

            LOGGER.debug { "Plugin ${BuildConfig.NAME_SHORT} - Started and Connected to Touch Portal" }

            LOGGER.debug { "Plugin Java VM Version:        ${System.getProperty("java.version")}" }

            LOGGER.debug { "Plugin Java Version Target:    ${BuildConfig.TARGET_JRE_SPEC}" }
            LOGGER.debug { "Plugin JDK Build Version:      ${BuildConfig.BUILD_JDK_SPEC}" }

            LOGGER.debug { "Plugin uses Touch Portal JRE:  ${BuildConfig.USES_TP_BUNDLED_JRE}" }

            LOGGER.debug { "Plugin Version Full Name:      ${BuildConfig.VERSION_NAME_FULL}" }

            LOGGER.debug {
                "Plugin Version Code / Base:    ${
                    BuildConfig.VERSION_CODE.toString().padStart(4, '0')
                } / ${BuildConfig.VERSION_NAME_BASE}"
            }
            LOGGER.debug { "Plugin is Build Release:       ${BuildConfig.BUILD_IS_RELEASE}" }

            if (!BuildConfig.BUILD_IS_RELEASE)
                LOGGER.debug { "Plugin Pre-release Version:    ${BuildConfig.BUILD_PRE_RELEASE_VERSION}" }


            LOGGER.debug { "Plugin Build Resources Bundle: ${BuildConfig.BUILD_RESOURCES_BUNDLE}" }

            LOGGER.debug { "Plugin Download Page URI:      ${BuildConfig.PLUGIN_RELEASES_DOWNLOAD_PAGE}" }
            LOGGER.debug { "Plugin Update/Releases URI:    ${BuildConfig.PLUGIN_RELEASES_UPDATE_CHECK_URI}" }


            // Start Instance Manager - Watches Veadotube Instance Folder and sends events to the receiver
            LOGGER.trace { "Construct Instance Manager" }
            instanceManager = InstancesManager(this)


            //Initialize Avatar State Updated Event
            triggerAvatarUpdatedEvent()

            updateTPConnectionSettingInfo()

            // Run Plugin Update Check
            runUpdateCheck()
        }
    }


    private fun updatePrimaryConnection(primaryNameOverwriteUpdated: Boolean = false) {
        veadoInstanceMapsLock.withLock {
            if (veadoInstanceMaps.getMiniInstanceListIsEmpty()) {
                oldestMiniInstance = null
                primaryMiniConnection = null
                return
            }

            if (oldestMiniInstance == null) {
                veadoInstanceMaps.runWithReadLock {
                    updateOldestMiniInstance()
                }
            }

            if (oldestMiniInstance != null) {
                if (primaryMiniConnection?.isConnected != true) primaryMiniConnection =
                    null // primary is not connected

                val needsUpdate = when {
                    primaryNameOverwriteUpdated -> true
                    primaryMiniConnection == null -> true
                    (settingVeadoPrimaryInstanceNameOverride.isBlank() &&
                            primaryMiniConnection?.instance != oldestMiniInstance) -> true

                    (settingVeadoPrimaryInstanceNameOverride.isNotEmpty() &&
                            primaryMiniConnection?.instance?.title?.contains(
                                settingVeadoPrimaryInstanceNameOverride,
                                ignoreCase = true
                            ) != true) -> true

                    else -> false
                }

                if (needsUpdate) {

                    if (settingVeadoPrimaryInstanceNameOverride.isNotEmpty()) {
                        // Primary Overwrite Name was Updated, Name is NOT empty
                        val newPrimaryConnectionCandidates =
                            veadoInstanceMaps.getConnectionsList()
                                .filter {
                                    it.name.contains(
                                        settingVeadoPrimaryInstanceNameOverride,
                                        ignoreCase = true
                                    )
                                }

                        val newPrimaryConnection =
                            if (newPrimaryConnectionCandidates.size == 1) newPrimaryConnectionCandidates[0]
                            else
                                newPrimaryConnectionCandidates
                                    .sortedWith(Connection.COMPARATOR_CONNECTION_BY_INSTANCE_TITLE_LENGTH_TIMESTAMP)
                                    .firstOrNull()


                        if (newPrimaryConnection != null) {
                            when (newPrimaryConnection) {
                                primaryMiniConnection -> { // Not Null, but Same
                                    LOGGER.trace { "Primary Instance left as '${newPrimaryConnection.instance.server}'; '${newPrimaryConnection.instance.title}'" }
                                }

                                else -> { // Not Null & Different
                                    primaryMiniConnection = newPrimaryConnection
                                    LOGGER.info { "Primary Instance Updated to '${newPrimaryConnection.instance.server}'; '${newPrimaryConnection.instance.title}'" }
                                }
                            }
                            return
                        }

                        // Continues as newPrimaryConnection was null
                        LOGGER.info { "Unable to find a match the Instance Override: '$settingVeadoPrimaryInstanceNameOverride'" }
                    }


                    if (primaryMiniConnection == null ||
                        (settingVeadoPrimaryInstanceNameOverride.isBlank() &&
                                primaryMiniConnection?.instance != oldestMiniInstance)
                    ) {
                        // If no Override (or Override not matched) find newest
                        val newPrimaryConnectionFallback = oldestMiniInstance?.id?.let {
                            veadoInstanceMaps.getConnectionByInstanceID(it)
                        }

                        when {
                            newPrimaryConnectionFallback == null -> {
                                primaryMiniConnection = null
                                LOGGER.info { "Unable to find a Primary Connection" }
                            }

                            newPrimaryConnectionFallback != primaryMiniConnection -> {
                                // Not Null & Different
                                primaryMiniConnection = newPrimaryConnectionFallback
                                LOGGER.info { "Primary Instance Updated to '${newPrimaryConnectionFallback.instance.server}'; '${newPrimaryConnectionFallback.instance.title}'" }
                            }

                            else -> {
                                // Not Null, but Same
                                LOGGER.trace { "Primary Instance left as '${newPrimaryConnectionFallback.instance.server}'; '${newPrimaryConnectionFallback.instance.title}'" }
                            }
                        }

                    }

                }
            }

            updateTPConnectionSettingInfo()
        }
    }


    ///**
    // * Requests [stateCurrentAvatarStateId] from [primaryConnection]
    // */
    //@Deprecated(
    //    "Use sendRequestMiniStateThumbnail with primaryConnection as value",
    //    ReplaceWith("sendRequestMiniStateThumbnail")
    //)
    //private fun sendRequestCurrentStateThumbnail() = kotlin.runCatching {
    //    primaryConnection?.let {
    //        if (stateCurrentAvatarStateId.isNotBlank()) {
    //            try {
    //                primaryConnection?.send(
    //                    channel = channelNodes,
    //                    requestData = VeadoRequest.createThumbnailStateMini(stateCurrentAvatarStateId)
    //                )
    //            } catch (ex: Exception) {
    //                LOGGER.warn { "Failed to Request Current Avatar State Thumbnail for ${it.connUri}: ${ex.message}" }
    //            }
    //        }
    //    }
    //}
    // TODO Remove

    private fun updateTPConnectionSettingInfo() {
        veadoInstanceMapsLock.withLock {
            // Update connected Instances Count
            val connectedInstanceCount = veadoInstanceMaps.getConnectionCount()

            this.sendSettingUpdate(
                VeadoTouchPluginConstants.Settings.SettingVeadoInstanceCount.NAME,
                connectedInstanceCount.toString(),
                false
            )

            // Update Default/Oldest Instance info
            val conn = primaryMiniConnection

            if (conn != null) {

                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceServer.NAME,
                    /* value = */       conn.server,
                    /* allowEmptyValue = */ false
                )

                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceName.NAME,
                    /* value = */       conn.instance.title,
                    /* allowEmptyValue = */ false
                )
            } else {
                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceServer.NAME,
                    /* value = */       "Awaiting Connection to Veadotube",
                    /* allowEmptyValue = */ true
                )

                this.sendSettingUpdate(
                    /* settingName = */ VeadoTouchPluginConstants.Settings.SettingVeadoPrimaryInstanceName.NAME,
                    /* value = */       "Awaiting Connection to Veadotube",
                    /* allowEmptyValue = */ true
                )
            }
        }
    }


    override fun onBroadcast(tpBroadcastMessage: TPBroadcastMessage) {
        LOGGER.trace { "onBroadcast ${tpBroadcastMessage.event}; ${tpBroadcastMessage.type}; ${tpBroadcastMessage.pageName}" }
    }


    override fun onSettings(tpSettingsMessage: TPSettingsMessage) {
        LOGGER.debug { "onSettings ${tpSettingsMessage.settings}" }

        if (settingVeadoPrimaryInstanceNameOverrideExisting != settingVeadoPrimaryInstanceNameOverride) {
            settingVeadoPrimaryInstanceNameOverrideExisting = settingVeadoPrimaryInstanceNameOverride

            updatePrimaryConnection(true)
        }


        if (settingVeadoAutoRequestThumbnailExisting != settingVeadoAutoRequestThumbnail) {
            settingVeadoAutoRequestThumbnailExisting = settingVeadoAutoRequestThumbnail

            if (
                settingVeadoAutoRequestThumbnail.isNotBlank() && (
                        settingVeadoAutoRequestThumbnail.contains("en", ignoreCase = true) ||
                                settingVeadoAutoRequestThumbnail.contains("y", ignoreCase = true) ||
                                settingVeadoAutoRequestThumbnail.contains("tr", ignoreCase = true)
                        )
            ) {

                if (!settingVeadoAutoRequestThumbnailEnabled) {
                    settingVeadoAutoRequestThumbnailEnabled = true
                    //Send Peek request - when the reply is received, png will be checked, etc.
                    primaryMiniConnection?.let { sendRequestMiniAvatarStatePeek(it) }
                }

            } else {
                settingVeadoAutoRequestThumbnailEnabled = false
            }

        }
    }


    override fun onNotificationOptionClicked(tpNotificationOptionClickedMessage: TPNotificationOptionClickedMessage) {
        LOGGER.debug { "onNotificationOptionClicked - Received Notification: ID = ${tpNotificationOptionClickedMessage.notificationId} - Option ID = ${tpNotificationOptionClickedMessage.optionId}" }
        //TODO setup notifications

        if (tpNotificationOptionClickedMessage.notificationId.startsWith(NotificationHelper.NOTIFICATION_UPDATE_ID)) {
            // Update Notification Clicked
            LOGGER.debug { "onNotificationOptionClicked - received matches plugin Notification ID" }

            processUpdateNotification(tpNotificationOptionClickedMessage, updateReleaseData)

        }
    }


    /* Instances Listener Functions */
    /**
     * Instance Manager - New Instance found
     */
    override fun onInstanceStart(instance: Instance) {
        // Get Instance Set for Instance ID, create, add and return a new one if it doesn't exist
        // > For Mini, only one will exist where Name = Title
        // > Future Versions may have more than one

        veadoInstanceMapsLock.withLock {

            LOGGER.trace { "onInstanceStart: Instance: $instance}" }
            // Add Instance to Map
            synchronized(veadoInstanceMaps) {

                // Create Connection and add to Connection Collection
                LOGGER.trace { "onInstanceStart: Construct Connection ${instance.server} ${instance.title}" }

                val newConnection = instance.connect(this, "TouchPortal-${instance.id}")

                // Add to new maps collection
                veadoInstanceMaps.onConnectionStart(newConnection)


                if (oldestMiniInstance == null ||
                    instance.id.timestamp < (oldestMiniInstance?.id?.timestamp ?: Long.MIN_VALUE)
                ) {
                    // Set with this instance of oldestInstance if null or current inst is older than current
                    oldestMiniInstance = instance
                }

                updatePrimaryConnection()
            }
        }
    }


    /**
     * Instance Manager Event - Existing Instance Updated
     *
     * Usually a 'Name' or Server IP change, requiring a full reset reconnection
     */
    override fun onInstanceChangeMajor(instance: Instance, oldInstance: Instance) {
        veadoInstanceMapsLock.withLock {
            if (oldInstance.server != instance.server) {
                //More changed
                LOGGER.debug { "onInstanceChangeMajor: run instanceConnectionCloseAndCleanup with ${oldInstance.server} ${oldInstance.title}" }
                instanceConnectionCloseAndCleanup(oldInstance)

                LOGGER.trace { "onInstanceChangeMajor: run OnConnect with ${instance.server} ${instance.title}" }
                onInstanceStart(instance)
                veadoInstanceMaps.onInstanceStart(instance)
            }

            updatePrimaryConnection()
        }
    }


    /**
     * Instance Manager Event - Existing Instance Updated
     *
     * A Minor change like a Window Title changing, not requiring reconnection
     */
    override fun onInstanceChangeMinor(instance: Instance, change: InstanceChange, oldValue: String) {
        veadoInstanceMapsLock.withLock {

            when (change) {
                InstanceChange.NAME -> {
                    //Just Name changed
                    LOGGER.debug { "onInstanceChangeMinor: Updated ${instance.server} title: '$oldValue' > '${instance.title}'" }

                    // Update Linked Hash Map - Remove Old Title Key, add connection against new key if it existed
                    veadoInstanceMaps.updateInstanceName(instance, oldValue)
                }
            }

            updatePrimaryConnection()
        }
    }


    /**
     * Instance Manager Event - Existing Instance Closed
     */
    override fun onInstanceEnd(id: InstanceID) {
        veadoInstanceMapsLock.withLock {
            LOGGER.trace { "onInstanceEnd: End $id" }

            instanceIdConnectionCloseAndCleanup(id)

            updatePrimaryConnection()
        }
    }

    /**
     * Close and Cleanup all Instances/Connections linked to an InstanceID
     */
    private fun instanceConnectionCloseAndCleanup(instance: Instance) {
        LOGGER.trace { "instanceCloseAndCleanup: Close and cleanup instance ${instance.server} ${instance.title} " }

        // Remove connection from Collection and make sure connection is closed
        veadoInstanceMapsLock.withLock {

            veadoInstanceMaps.instanceConnectionCloseAndCleanup(instance)?.let { connectionToEnd ->
                LOGGER.trace { "instanceConnectionCloseAndCleanup: Close Connection ${connectionToEnd.server} ${connectionToEnd.name}" }

                if (connectionToEnd == primaryMiniConnection) {
                    // Clear Current State
                    //sendStateClearCurrentAvatarState() // TODO Remove
                    sendStateClearCurrentAvatarStateName()
                    sendStateClearCurrentAvatarStateThumbnail()
                    //sendStateClearCurrentAvatarStateId() // TODO Remove
                    sendChoiceClearCurrentAvatarState()
                }
                connectionToEnd.close()
            }
        }
    }


    private fun updateOldestMiniInstance() {
        veadoInstanceMapsLock.withLock {
            val inst = veadoInstanceMaps.getOldestMiniInstance()
            if (inst != null) {
                val oldInst = oldestMiniInstance
                if (oldInst == null ||
                    inst.id.timestamp < oldInst.id.timestamp
                ) {
                    // Set with this instance of oldestInstance if null or current inst is older than current
                    oldestMiniInstance = inst
                }
                return
            }

            oldestMiniInstance = null
            primaryMiniConnection = null
        }
    }


    /**
     * Close and Cleanup all Instances/Connections linked to an InstanceID
     */
    private fun instanceIdConnectionCloseAndCleanup(id: InstanceID) {
        LOGGER.trace { "instanceCloseAndCleanup: Close and cleanup instance $id " }

        // Remove connection from Collection and make sure connection is closed
        veadoInstanceMapsLock.withLock {

            veadoInstanceMaps.instanceIdRemove(id)?.forEach { connectionToEnd ->
                LOGGER.trace { "onInstanceEnd: Close Connection ${connectionToEnd.server} ${connectionToEnd.name}" }

                if (connectionToEnd == primaryMiniConnection) {
                    // Clear Current State
                    //sendStateClearCurrentAvatarState() // TODO Remove
                    sendStateClearCurrentAvatarStateName()
                    sendStateClearCurrentAvatarStateThumbnail()
                    //sendStateClearCurrentAvatarStateId() // TODO Remove
                    sendChoiceClearCurrentAvatarState()
                }

                connectionToEnd.close()
            }

            //Check if oldest instance is Ended
            if (oldestMiniInstance?.id == id) {
                oldestMiniInstance = null
                //If oldest removed, try and find a replacement

                updateOldestMiniInstance()
            }
        }
    }


    /* Connection Listener Functions */
    override fun onConnectionError(connection: Connection, error: ConnectionError, exception: Exception?): Boolean {
        // Veadotube Connection Error
        LOGGER.trace { "onConnectionError: Connection ${connection.connUri}, Error ${error.name}" }

        // Whether the connection is told to cancel at the end
        var returnCancelConnection = false

        veadoInstanceMapsLock.withLock {

            when (error) {
                ConnectionError.FailedToConnect -> {
                    // Failed to connect
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Failed to Connect: ${exception?.message}" }
                    returnCancelConnection = true
                    connection.close()
                    instanceManager?.markInstanceFailed(connection.instance.id)
                }

                ConnectionError.ExceededRetries -> {
                    // Terminal, tell Manager to clear from known list
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Connect Retries Exceeded" }
                    returnCancelConnection = true // Ignored, terminal in constructor
                    connection.close()
                    instanceManager?.markInstanceFailed(connection.instance.id)
                }

                ConnectionError.InvalidServerOrName -> {
                    /* Terminal */
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Invalid Server Or Name" }
                    returnCancelConnection = true // Ignored in constructor
                    instanceManager?.markInstanceFailed(connection.instance.id)
                }

                ConnectionError.Unknown -> {
                    /* Log but let Connection continue */
                    LOGGER.debug { "onConnectionError: Connection ${connection.server} ${connection.name}, Error: ${exception?.message}" }
                }
            }


            if (!veadoInstanceMaps.isConnectionInCollection(connection)) {
                // If Connection is not in Collection, make sure it closes.
                // Otherwise, it will retry several times before giving up
                connection.close()
            }
        }

        return returnCancelConnection
    }


    override fun onConnectionChange(connection: Connection, active: Boolean) {
        LOGGER.trace { "onConnectionChange: Connection ${connection.connUri}, Active $active" }
        veadoInstanceMapsLock.withLock {
            // Veadotube Connection Activated/Up or Deactivated/Down
            if (active) {
                /* Connection Marked active */
                veadoInstanceMaps.onConnectionActivate(connection)

                sendRequestNodeList(connection)

                // Request list of possible States
                sendRequestMiniAvatarStateList(connection)

                // Request Current State
                sendRequestMiniAvatarStatePeek(connection)

                // Start State Listener
                sendRequestMiniStartListener(connection)

            } else {
                /* Connection Marked inactive */

                //Stop Listener
                sendRequestMiniStopListener(connection)

                veadoInstanceMaps.cleanupConnectionStates(connection)

            }
        }
    }


    override fun onConnectionReceive(connection: Connection, message: ResultMessage) {
        // Receive message from Veadotube
        LOGGER.debug { "onConnectionReceive: -> Connection ${connection.connUri} from Channel ${message.channel} received ${message.event} Message" }

        when (message) {
            is ResultMessage.ResultMessageWithInstanceInfo -> {
                LOGGER.debug { "onConnectionReceive: Instance Info" }
                LOGGER.trace { "Message -> Channel: ${message.channel}" }
                LOGGER.trace { "Message -> ID:      ${message.id}" }
                LOGGER.trace { "Message -> Name:    ${message.name}" }
                LOGGER.trace { "Message -> Server:  ${message.server}" }
                LOGGER.trace { "Message -> Version: ${message.version}" }
            }

            is ResultMessage.ResultMessageWithPayloadBoolean -> {
                LOGGER.debug { "onConnectionReceive: Message Payload Boolean" }
                LOGGER.trace { "Message -> ID:      ${message.id}" }
                LOGGER.trace { "Message -> Type:    ${message.type}" }
                LOGGER.trace { "Message -> Name:    ${message.name}" }
                LOGGER.trace { "Message -> Payload: ${message.payload}" }
            }

            is ResultMessage.ResultMessageWithPayloadNumber -> {
                LOGGER.debug { "onConnectionReceive: Message Payload Number" }
                LOGGER.trace { "Message -> ID:          ${message.id}" }
                LOGGER.trace { "Message -> Type:        ${message.type}" }
                LOGGER.trace { "Message -> Name:        ${message.name}" }
                LOGGER.trace { "Message -> Payload Val: ${message.payload.value}" }
                LOGGER.trace { "Message -> Payload Max: ${message.payload.min ?: "null"}" }
                LOGGER.trace { "Message -> Payload Min: ${message.payload.max ?: "null"}" }
            }

            is ResultMessage.ResultMessageWithEntryList -> {
                // Result from request: `nodes:{"event": "list"}`
                // This returns the entries - e.g. stateEvents - avatar state.
                // These values are sent in other request types
                // Mini just uses stateEvents, so currently we just assume id = mini and type = stateEvents
                // instead of requesting them first but this might change with other versions (Full, etc.)

                LOGGER.debug { "onConnectionReceive: Message List -> Entry List (${message.entries.count()} Items)" }

                for (entry in message.entries) {
                    LOGGER.trace { "onConnectionReceive: Message -> Entry > Type: ${entry.type}; ID: ${entry.id}; Name: ${entry.name}" }
                }
            }

            is ResultMessage.ResultMessageWithPayload -> {
                LOGGER.debug { "onConnectionReceive: Message Payload" }
                LOGGER.trace { "Message -> ID:   ${message.id}" }
                LOGGER.trace { "Message -> Type: ${message.type}" }
                LOGGER.trace { "Message -> Name: ${message.name}" }

                when (val payload = message.payload) {
                    is BleatkanStatePeek -> {
                        // Peek result - could be Peek Request, Listener, etc.
                        LOGGER.debug { "onConnectionReceive: Message Payload -> Peek (${payload.state})" }
                        processReceivedPayloadPeek(connection, payload)
                    }

                    is BleatkanStateList -> {
                        // List of States - Received in order that they appear in Program
                        LOGGER.debug { "onConnectionReceive: Message Payload -> State List (${payload.states.count()} Items)" }
                        processReceivedPayloadAvatarStateList(connection, payload)
                    }

                    is BleatkanStateThumbnail -> {
                        // Thumb result - thumbnail for an Avatar State
                        LOGGER.debug { "onConnectionReceive: Message Payload -> Thumbnail" }
                        processReceivedPayloadThumbnail(connection, payload)
                    }
                }
            }

            else -> {
                LOGGER.error { "onConnectionReceive: Unknown Message Payload" }
                LOGGER.error { "Message -> Channel: ${message.channel}" }
                LOGGER.error { "Message -> Event:   ${message.event}" }
            }

        }
    }


    /**
     * Veadotube Connection Update - Message Received
     *
     * @param connection Connection providing update
     * @param payload State List Data Received
     */
    private fun processReceivedPayloadAvatarStateList(
        connection: Connection,
        payload: BleatkanStateList
    ) {
        LOGGER.debug { "processReceivedPayloadAvatarStateList: Update Collection Maps" }
        synchronized(connection) {
            // Add/Replace existing Lists/Maps
            veadoInstanceMaps.getConnectionData(connection)?.updateStates(payload)

            onUpdateAvatarStateList(connection)
        }
    }


    /**
     * Call when Peek Message Received - updates State ID/Name, etc. and sends to Touch Portal
     *
     * We may not have the state name yet - if not, a State Request should be sent
     *
     * @param connection Connection providing update
     * @param payload State Peek Data Received
     */
    private fun processReceivedPayloadPeek(
        connection: Connection,
        payload: BleatkanStatePeek
    ) {
        LOGGER.trace { "Message -> Payload -> Event: ${payload.event}, State: ${payload.state}" }

        synchronized(connection) {
            // Update Current State
            val connData = veadoInstanceMaps.getConnectionData(connection)

            if (connData != null) {

                // Update value, return if it nothing is updated (false) - possible if Peek requests are sent but there's no update
                if (!connData.updateCurrentState(payload)) return

                val stateCurrent = connData.currentState

                //sendStateUpdateCurrentAvatarStateId(payload.state) //TODO Remove

                if (stateCurrent != null) {
                    //If we have the name, update to Touch Portal
                    //sendStateUpdateCurrentAvatarState(connection, stateCurrent) //TODO Remove

                    //Name value
                    val stateCurrentName = stateCurrent.name
                    if (stateCurrentName.isNullOrEmpty()) {
                        //If we don't have the name, send request for fresh state list
                        sendRequestMiniAvatarStateList(connection)
                    } else {
                        try {
                            sendStateUpdateCurrentAvatarStateName(stateCurrentName)
                        } catch (_: Exception) {/* Do nothing */
                        }
                    }

                    if (settingVeadoAutoRequestThumbnailEnabled) {
                        when (val png = stateCurrent.thumbnail?.png) {
                            null -> sendRequestMiniStateThumbnail(connection, stateCurrent.id)
                            else -> sendStateUpdateCurrentAvatarStateThumbnail(png)
                        }
                    }
                }

            } else {
                LOGGER.debug { "updateCurrentAvatarStateId: couldn't find collConnectionData for ${connection.connUri}" }
            }
        }
    }


//    /**
//     * Call when Current State has updated - updates name and sends to Touch Portal
//     *
//     * e.g. State Names may have Changed, etc.
//     *
//     * Probably obsolete
//     */
//    @Deprecated("Obsolete")
//    private fun onCurrentStateNameUpdated(connection: Connection) {
//        // Update current state name
//        synchronized(connection) {
//
//            //Get current State for Connection
//            val currentState = collConnectionData[connection]?.currentState
//            LOGGER.debug { "updateCurrentStateName: Got Current State $currentState" }
//
//            if (currentState != null) {
//                //If not null, send
//
//                sendStateUpdateCurrentAvatarState(connection, currentState)
//
//                sendStateUpdateCurrentAvatarStateName(currentState.name ?: "Unknown")
//
//            }
//        }
//    }
// TODO Remove

    private fun processReceivedPayloadThumbnail(connection: Connection, payload: BleatkanStateThumbnail) {
        LOGGER.trace { "Message -> Payload -> Event/State:  ${payload.event}; ${payload.state}" }
        LOGGER.trace { "Message -> Payload -> Height/Width: ${payload.height}/${payload.width}" }
        LOGGER.trace { "Message -> Payload -> PNG B64 Chars: ${payload.png.count()}" }


        val collData = veadoInstanceMaps.getConnectionData(connection) ?: return

        // Update Thumbnail - May need to process image to make it square
        val updated: Boolean = collData.updateStateThumbnail(payload)

        collData.currentState.let { currState ->

            if (currState?.id == payload.state) {

                currState.thumbnail?.png?.let { png ->
                    if (updated || statePrimaryMiniCurrentAvatarStateThumbnail != png) {
                        // If matches current state, update Touch Portal
                        sendStateUpdateCurrentAvatarStateThumbnail(png)
                    }
                }
            }
        }
    }


    /**
     * Token for Listener
     */
    private val listenerToken = "TpVtPlugin.ChangeState"

    /**
     * Token for Listener
     */
    private val listenerTokenBase = "TpVtPlugin"

    /**
     * Nodes Channel
     *
     * Default channel used in Mini
     */
    private val channelNodes = "nodes"

    /**
     * Instance Channel - channel used to get Instance Info similar to Instance File
     */
    private val channelInstance = "instance"


//    /**
//     * Actions for updating the Current Avatar State in Touch Portal etc.
//     *
//     * State and State Name, etc
//     *
//     * @see stateCurrentAvatarState
//     */
//    @Suppress("DEPRECATION")
//    private fun sendStateUpdateCurrentAvatarState(
//        connection: Connection,
//        state: VtState,
//        allowEmptyValue: Boolean = false,
//        forceUpdate: Boolean = false
//    ) {
//        // State ID is different pre 2.1 - from 2.1 it's just the name
//        val stateString = if (connection.compatibilityFlagMiniPre2dot1) {
//            // Generate String with Name and ID - pre 2.1
//            avatarStateToString(state.id, state.name ?: "Unknown")
//        } else {
//            // ID is just name
//            state.id
//        }
//        stateCurrentAvatarState = stateString
//
//        // Update State - do this first in case Plugin State is used for checks
//        this.sendStateUpdate(
//            VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarState.ID,
//            stateString,
//            /* allowEmptyValue = */ allowEmptyValue,
//            /* forceUpdate = */ forceUpdate
//        )
//
//    }
// TODO Remove

//    /**
//     * Action for clearing the Current Avatar State in Touch Portal etc.
//     *
//     * State and State Name, etc
//     *
//     * @see stateCurrentAvatarState
//     */
//    private fun sendStateClearCurrentAvatarState() {
//        stateCurrentAvatarState = ""
//
//        // Update State - do this first in case Plugin State is used for checks
//        this.sendStateUpdate(
//            VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarState.ID,
//            stateCurrentAvatarState,
//        )
//
//    }
// TODO Remove

//    /**
//     * Actions for updating the Current Avatar State ID in Touch Portal etc.
//     *
//     * State ID Only
//     *
//     * @see stateCurrentAvatarStateId
//     */
//    private fun sendStateUpdateCurrentAvatarStateId(
//        stateID: String,
//        allowEmptyValue: Boolean = false,
//        forceUpdate: Boolean = false
//    ) {
//        stateCurrentAvatarStateId = stateID
//
//        // Update State - do this first in case Plugin State is used for checks
//        this.sendStateUpdate(
//            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateId.ID,
//            /* value = */ stateCurrentAvatarStateId,
//            /* allowEmptyValue = */ allowEmptyValue,
//            /* forceUpdate = */ forceUpdate
//        )
//
//    }
// TODO Remove

//    /**
//     * Actions for clearing the Current Avatar State ID in Touch Portal etc.
//     *
//     * State ID Only
//     *
//     * @see stateCurrentAvatarStateId
//     */
//    private fun sendStateClearCurrentAvatarStateId() {
//        stateCurrentAvatarStateId = ""
//
//        // Update State - do this first in case Plugin State is used for checks
//        this.sendStateUpdate(
//            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateId.ID,
//            /* value = */ stateCurrentAvatarStateId,
//            /* allowEmptyValue = */ true,
//            /* forceUpdate = */ false
//        )
//
//    }
// TODO Remove

    /**
     * Actions for updating the Current Avatar State Name in Touch Portal etc.
     *
     * State Name Only
     *
     * @see statePrimaryMiniCurrentAvatarStateName
     */
    private fun sendStateUpdateCurrentAvatarStateName(
        stateName: String,
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        statePrimaryMiniCurrentAvatarStateName = stateName

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateName.ID,
            /* value = */ statePrimaryMiniCurrentAvatarStateName,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )

    }


    private fun sendStateClearCurrentAvatarStateName() {
        statePrimaryMiniCurrentAvatarStateName = ""

        // Update State - do this first in case Plugin State is used for checks
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateName.ID,
            /* value = */ statePrimaryMiniCurrentAvatarStateName,
            /* allowEmptyValue = */ true,
            /* forceUpdate = */ false
        )
    }


    /**
     * Actions for updating the Current Avatar State Thumbnail in Touch Portal etc.
     *
     * State Thumbnail Only
     *
     * @see statePrimaryMiniCurrentAvatarStateName
     */
    private fun sendStateUpdateCurrentAvatarStateThumbnail(
        stateThumbnail: String,
        allowEmptyValue: Boolean = false,
        forceUpdate: Boolean = false
    ) {
        statePrimaryMiniCurrentAvatarStateThumbnail = stateThumbnail

        // Update State
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateThumbnail.ID,
            /* value = */ statePrimaryMiniCurrentAvatarStateThumbnail,
            /* allowEmptyValue = */ allowEmptyValue,
            /* forceUpdate = */ forceUpdate
        )
    }


    /**
     * Actions for updating the Current Avatar State Thumbnail in Touch Portal etc.
     *
     * State Thumbnail Only
     *
     * @see statePrimaryMiniCurrentAvatarStateName
     */
    private fun sendStateClearCurrentAvatarStateThumbnail() {
        statePrimaryMiniCurrentAvatarStateThumbnail = ""

        // Update State
        this.sendStateUpdate(
            /* stateId = */ VeadoTouchPluginConstants.PrimaryInstance.States.CurrentAvatarStateThumbnail.ID,
            /* value = */ statePrimaryMiniCurrentAvatarStateThumbnail,
            /* allowEmptyValue = */ true,
            /* forceUpdate = */ false
        )
    }


    /**
     * Actions for updating the Choices for [actionSetAvatarStateFromList] and [stateCurrentAvatarState] in Touch Portal
     *
     * @see actionSetAvatarStateFromList
     */
    private fun sendChoiceUpdateCurrentAvatarState(choices: ArrayList<String>) {
        LOGGER.trace { "sendChoiceUpdateCurrentAvatarState: Sending choices: $choices" }

        // Update State Choices
        val toTypedArray = choices.toTypedArray()

        this.sendChoiceUpdate(
            VeadoTouchPluginConstants.PrimaryInstance.Actions.SetAvatarStateFromList.Choices.ID,
            toTypedArray
        )
        //        //Disabled, Event removed for now
        //        this.sendChoiceUpdate(
        //            VeadoTouchPluginConstants.PrimaryInstance.Events.CurrentAvatarState.ID,
        //            toTypedArray
        //        )
    }


    /**
     * Actions for updating the Choices for [actionSetAvatarStateFromList] and [stateCurrentAvatarState] in Touch Portal
     *
     * @see actionSetAvatarStateFromList
     */
    private fun sendChoiceClearCurrentAvatarState() {
        LOGGER.trace { "sendChoiceUpdateCurrentAvatarState: Clearing Choices" }

        // Clear State Choices
        val toTypedArray = Array(1) { "" }

        this.sendChoiceUpdate(
            /* listId = */ VeadoTouchPluginConstants.PrimaryInstance.Actions.SetAvatarStateFromList.Choices.ID,
            /* values = */ toTypedArray,
            /* allowEmptyArrayValues = */ true
        )

        //        //Disabled, Event removed for now
        //        this.sendChoiceUpdate(
        //            /* listId = */ VeadoTouchPluginConstants.PrimaryInstance.Events.CurrentAvatarState.ID,
        //            /* values = */ toTypedArray,
        //            /* allowEmptyArrayValues = */ true
        //        )
    }


    /* Veado Requests */
    private fun sendRequestInstanceInfo(connection: Connection) {
        try {
            connection.send(
                channel = channelInstance,
                requestData = VeadoRequest.getEventInfo
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Instance Info for ${connection.connUri}: ${ex.message}" }
        }
    }

    private fun sendRequestNodeList(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                requestData = VeadoRequest.getEventList
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Node List for ${connection.connUri}: ${ex.message}" }
        }
    }

    private fun sendNodesListenerEnable(connection: Connection, channel: String = channelNodes) {
        try {
            println("Send enable nodes listener")
            connection.send(
                channel = channel,
                RequestMessage.RequestMessageNodeEventToken(
                    event = PayloadEvent.LISTEN.value,
                    token = "$listenerTokenBase.$channelNodes"
                )
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Enable Node Listener for ${connection.connUri}; ${channel}: ${ex.message}" }
        }
    }

    private fun sendNodesListenerDisable(connection: Connection, channel: String = channelNodes) {
        try {
            println("Send enable nodes listener")
            connection.send(
                channel = channel,
                RequestMessage.RequestMessageNodeEventToken(
                    event = PayloadEvent.UNLISTEN.value,
                    token = "$listenerTokenBase.$channelNodes"
                )
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Disable Node Listener for ${connection.connUri}; ${channel}: ${ex.message}" }
        }
    }

    private fun sendRequestNodeStateEventsList(
        connection: Connection,
        channel: String = channelNodes,
        nodeId: String = MessagePayloadId.MINI.value
    ) {
        try {
            connection.send(
                channel = channel,
                requestData = RequestMessageNodeEvent(
                    event = MessageEvent.PAYLOAD.value,
                    type = MessagePayloadType.STATE_EVENTS.value,
                    id = nodeId,
                    payload = getPayloadEventList
                )
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request State List for ${connection.connUri}; ${channel}; ${nodeId}: ${ex.message}" }
        }
    }

    private fun sendRequestNodeNumberList(
        connection: Connection,
        channel: String = channelNodes,
        nodeId: String
    ) {
        try {
            connection.send(
                channel = channel,
                requestData = RequestMessageNodeEvent(
                    event = MessageEvent.PAYLOAD.value,
                    type = MessagePayloadType.NUMBER.value,
                    id = nodeId,
                    payload = getPayloadEventList
                )
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request State List for ${connection.connUri}; ${channel}; ${nodeId}: ${ex.message}" }
        }
    }

    private fun sendRequestNodeBooleanList(
        connection: Connection,
        channel: String = channelNodes,
        nodeId: String
    ) {
        try {
            connection.send(
                channel = channel,
                requestData = RequestMessageNodeEvent(
                    event = MessageEvent.PAYLOAD.value,
                    type = MessagePayloadType.BOOLEAN.value,
                    id = nodeId,
                    payload = getPayloadEventList
                )
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request State List for ${connection.connUri}; ${channel}; ${nodeId}: ${ex.message}" }
        }
    }

    private fun sendRequestNodeStateGet(
        connection: Connection,
        channel: String = channelNodes,
        nodeId: String
    ) {
        require(nodeId.isNotBlank()) { "Node ID can't be blank" }
        try {
            connection.send(
                channel = channel,
                requestData = RequestMessageNodeEvent(
                    event = MessageEvent.PAYLOAD.value,
                    type = MessagePayloadType.STATE_EVENTS.value,
                    id = nodeId,
                    payload = getPayloadEventGet
                )
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Get Current State for ${connection.connUri}; ${channel}; ${nodeId}: ${ex.message}" }
        }
    }

    private fun sendRequestNodeBooleanGet(
        connection: Connection,
        channel: String = channelNodes,
        nodeId: String
    ) {
        require(nodeId.isNotBlank()) { "Node ID can't be blank" }
        try {
            connection.send(
                channel = channel,
                requestData = RequestMessageNodeEvent(
                    event = MessageEvent.PAYLOAD.value,
                    type = MessagePayloadType.BOOLEAN.value,
                    id = nodeId,
                    payload = getPayloadEventGet
                )
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Get Current State for ${connection.connUri}; ${channel}; ${nodeId}: ${ex.message}" }
        }
    }

    private fun sendRequestMiniAvatarStateList(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                requestData = VeadoRequest.getListStateMini
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request State List for ${connection.connUri}: ${ex.message}" }
        }
    }

    private fun sendRequestMiniAvatarStatePeek(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                requestData = VeadoRequest.getPeekStateMini
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Current State for ${connection.connUri}: ${ex.message}" }
        }
    }

    /**
     * Send request for Push-To-Talk Mic Input
     *
     * Warning:
     * * Enabling Push-to-Talk 'Mutes' the Microphone input
     * until an API message to toggle/unmute is sent
     * * If a hotkey is set, API won't work
     *
     * @param sendValue
     * * true > PPT Node 'enabled' > Mic Unmuted
     * * false > PPT Node 'disabled' > Mic Muted
     * * null > Toggle
     *
     */
    private fun sendRequestMiniPushToTalkMicInput(connection: Connection, sendValue: Boolean? = null) {
        try {
            val pushToTalk = if (sendValue != null) {
                VeadoRequest.createRequestWithPayload(
                    event = MessageEvent.PAYLOAD,
                    type = MessagePayloadType.BOOLEAN,
                    id = MessagePayloadId.MINI,
                    payloadEvent = PayloadEvent.SET,
                    payloadValue = sendValue
                )
            } else {
                VeadoRequest.createRequestWithPayload(
                    event = MessageEvent.PAYLOAD,
                    type = MessagePayloadType.BOOLEAN,
                    id = MessagePayloadId.MINI,
                    payloadEvent = PayloadEvent.TOGGLE
                )
            }
            LOGGER.trace { "sendRequestMiniPushToTalkMicInput: $pushToTalk" }
            connection.send(
                channel = channelNodes,
                requestData = pushToTalk
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Set Push To Talk for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestMiniStateThumbnail(connection: Connection, stateID: String) {
        try {
            connection.send(
                channel = channelNodes,
                requestData = VeadoRequest.createThumbnailStateMini(stateID)
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Current State Thumbnail for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestMiniStartListener(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                VeadoRequest.createListenStateMini(listenerToken)
            )
        } catch (ex: Exception) {
            LOGGER.warn { "Failed to Request Listener Start for ${connection.connUri}: ${ex.message}" }
        }
    }


    private fun sendRequestMiniStopListener(connection: Connection) {
        try {
            connection.send(
                channel = channelNodes,
                VeadoRequest.createUnlistenStateMini(listenerToken)
            )
        } catch (ex: Exception) {
            LOGGER.debug { "Failed to Request Listener Stop for ${connection.connUri}: ${ex.message}" }
        }
    }


    /* Start of functions for Update Checks */

    private var updateChecker: PluginUpdateChecker? = null

    /**
     * Check for newer Plugin Versions
     */
    private fun runUpdateCheck() {
        updateChecker = PluginUpdateChecker(veadotubePlugin, BuildConfig.PLUGIN_RELEASES_UPDATE_CHECK_URI)
    }

    /** Update Data */
    private var updateReleaseData: UpdateReleaseData? = null

    /** Release Data for Main Track Update */
    private var updateReleaseDataMain: ReleaseData? = null

    /** Release Data for Dev Track Update */
    private var updateReleaseDataDev: ReleaseData? = null

    /**
     * Process Received Update Check Result
     */
    override fun onUpdateCheckResult(updateData: UpdateReleaseData) {
        // Assign for use with notifications
        updateReleaseData = updateData

        if (updateData.updateAvailable) {
            // TODO Send notification
            // Check flagged as Manual (eg Breaking update) > updateManualRequired = true

            val updateMainBranchReleaseData = updateData.mainBranchReleaseData

            if (BuildConfig.BUILD_IS_RELEASE) {
                if (updateMainBranchReleaseData != null) {
                    // Build is Main Release, and Main has update
                    notifyReleaseUpdateMain(updateMainBranchReleaseData)

                } else {
                    LOGGER.warn { "Update Check: An Update is available but release information is missing. Please check ${BuildConfig.PLUGIN_RELEASES_UPDATE_CHECK_URI} for updates. Your Version: ${BuildConfig.VERSION_NAME_FULL}" }
                }

            } else {
                val updateBranchReleaseDataDev = updateData.devBranchReleaseData
                when {
                    updateMainBranchReleaseData != null && updateBranchReleaseDataDev == null -> {
                        // Main has update, Dev Version does not
                        notifyReleaseUpdateMain(updateMainBranchReleaseData)
                    }

                    updateMainBranchReleaseData == null && updateBranchReleaseDataDev != null -> {
                        // Dev Version has update, Main Version does not
                        notifyReleaseUpdateDev(updateBranchReleaseDataDev)
                    }

                    updateMainBranchReleaseData != null && updateBranchReleaseDataDev != null -> {
                        // Both Exist (Dev Version has update, Main also has update)
                        notifyReleaseUpdateBoth(updateMainBranchReleaseData, updateBranchReleaseDataDev)
                    }

                    else -> {
                        // Neither Exist - Shouldn't reach this
                        LOGGER.warn { "Update Check: An Update is available but release information is missing. Please check ${BuildConfig.PLUGIN_RELEASES_UPDATE_CHECK_URI} for updates. Your Version: ${BuildConfig.VERSION_NAME_FULL}" }
                    }

                }

            }


        } else {
            LOGGER.info { "Update Check: No update available" }
        }

        // Close & De-reference updateChecker
        updateChecker?.close().also { updateChecker = null }

    }


    /* Update Notification */

    private fun processUpdateNotification(
        tpNotificationOptionClickedMessage: TPNotificationOptionClickedMessage, relData: UpdateReleaseData?
    ) {

        if (relData == null) {
            LOGGER.debug { "onNotificationOptionClicked - Received NOTIFICATION_UPDATE_ID but updateReleaseData is null" }
            LOGGER.warn { "The update notification clicked is out of date or last check failed" }
            return
        }

        // Split ID on colon (:)
        // MAIN/DEV = UpdateIDs.(MAIN or DEV):<Version ID>
        // BOTH = UpdateIDs.BOTH:<Version ID (Main)>:<Version ID (Dev)>
        val notificationIdBreakdown = tpNotificationOptionClickedMessage.notificationId.split(':')

        val notificationId = notificationIdBreakdown[0].ifBlank { return }

        when (notificationId) {
            NotificationHelper.UpdateIDs.MAIN.id -> {
                // Main Update Notification
                val version = notificationIdBreakdown[1]
                LOGGER.debug { "onNotificationOptionClicked - Notification ID: Main - Version: $version" }

                val updateReleaseDataMain = updateReleaseDataMain

                if (updateReleaseDataMain == null) {
                    LOGGER.debug { "onNotificationOptionClicked - Received $version but updateReleaseDataMain is null" }
                    LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                    return
                }

                val versionInfo: ReleaseData =
                    if (version != updateReleaseDataMain.version) {
                        LOGGER.debug { "onNotificationOptionClicked - Received $version but updateReleaseDataMain is ${updateReleaseDataMain.version}" }
                        LOGGER.warn { "The update notification clicked may be out of date and a newer version is available" }

                        // Get selected version from map, etc
                        val newVerRelInfo: ReleaseData? =
                            updateReleaseData?.mainBranchData?.releaseMapByVersionString?.get(version)

                        // Check Again for new version fetched
                        if (newVerRelInfo == null) {
                            LOGGER.debug { "onNotificationOptionClicked - Received $version but unable to find version in Main Release list" }
                            LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                            return
                        }

                        newVerRelInfo
                    } else
                        updateReleaseDataMain


                // Process Notification
                NotificationHelper.respondNotificationClickedUpdateMain(
                    tpNotificationOptionClickedMessage,
                    versionInfo
                )

            }

            NotificationHelper.UpdateIDs.DEV.id -> {
                // Dev Update Notification
                val version = notificationIdBreakdown[1]
                LOGGER.debug { "onNotificationOptionClicked - Notification ID: Dev - Version: $version" }

                val updateReleaseDataDev = updateReleaseDataDev

                if (updateReleaseDataDev == null) {
                    LOGGER.debug { "onNotificationOptionClicked - Received $version but updateReleaseDataDev is null" }
                    LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                    return
                }

                val versionInfo: ReleaseData =
                    if (version != updateReleaseDataDev.version) {
                        LOGGER.debug { "onNotificationOptionClicked - Received $version but updateReleaseDataDev is ${updateReleaseDataDev.version}" }
                        LOGGER.warn { "The update notification clicked may be out of date and a newer version is available" }

                        // Get selected version from map, etc
                        val newVerRelInfo: ReleaseData? =
                            updateReleaseData?.devBranchData?.releaseMapByVersionString?.get(version)

                        // Check Again for new version fetched
                        if (newVerRelInfo == null) {
                            LOGGER.debug { "onNotificationOptionClicked - Received $version but unable to find version in Dev Release list" }
                            LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                            return
                        }

                        newVerRelInfo
                    } else
                        updateReleaseDataDev


                // Process Notification
                NotificationHelper.respondNotificationClickedUpdateDev(
                    tpNotificationOptionClickedMessage,
                    versionInfo
                )
            }

            NotificationHelper.UpdateIDs.BOTH.id -> {
                // Main and Dev Update Notification
                val versionMain = notificationIdBreakdown[1]
                val versionDev = notificationIdBreakdown[2]
                LOGGER.debug { "onNotificationOptionClicked - Notification ID: Both - Main Version: $versionMain - Dev Version: $versionDev" }


                val updateReleaseDataMain = updateReleaseDataMain

                if (updateReleaseDataMain == null) {
                    LOGGER.debug { "onNotificationOptionClicked - Received $versionMain but updateReleaseDataMain is null" }
                    LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                    return
                }

                val versionInfoMain: ReleaseData =
                    if (versionMain != updateReleaseDataMain.version) {
                        LOGGER.debug { "onNotificationOptionClicked - Received $versionMain but updateReleaseDataMain is ${updateReleaseDataMain.version}" }
                        LOGGER.warn { "The update notification clicked may be out of date and a newer version is available" }

                        // Get selected version from map, etc
                        val newVerRelInfo: ReleaseData? =
                            updateReleaseData?.mainBranchData?.releaseMapByVersionString?.get(versionMain)

                        // Check Again for new version fetched
                        if (newVerRelInfo == null) {
                            LOGGER.debug { "onNotificationOptionClicked - Received $versionMain but unable to find version in Main Release list" }
                            LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                            return
                        }

                        newVerRelInfo
                    } else
                        updateReleaseDataMain


                val updateReleaseDataDev = updateReleaseDataDev

                if (updateReleaseDataDev == null) {
                    LOGGER.debug { "onNotificationOptionClicked - Received $versionDev but updateReleaseDataDev is null" }
                    LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                    return
                }

                val versionInfo: ReleaseData =
                    if (versionDev != updateReleaseDataDev.version) {
                        LOGGER.debug { "onNotificationOptionClicked - Received $versionDev but updateReleaseDataDev is ${updateReleaseDataDev.version}" }
                        LOGGER.warn { "The update notification clicked may be out of date and a newer version is available" }

                        // Get selected version from map, etc
                        val newVerRelInfo: ReleaseData? =
                            updateReleaseData?.devBranchData?.releaseMapByVersionString?.get(versionDev)

                        // Check Again for new version fetched
                        if (newVerRelInfo == null) {
                            LOGGER.debug { "onNotificationOptionClicked - Received $versionDev but unable to find version in Dev Release list" }
                            LOGGER.warn { "The update notification clicked is out of date or last check failed" }
                            return
                        }

                        newVerRelInfo
                    } else
                        updateReleaseDataDev


                // Process Notification
                NotificationHelper.respondNotificationClickedUpdateBoth(
                    tpNotificationOptionClickedMessage,
                    versionInfoMain,
                    versionInfo
                )

            }

            else -> LOGGER.warn { "Unknown Notification Received" }
        }
    }

    private fun notifyReleaseUpdateMain(mainBranchReleaseData: ReleaseData) {
        val currVerName = BuildConfig.VERSION_NAME_BASE
        val currIntegrated = BuildConfig.USES_TP_BUNDLED_JRE

        val updtVerName = mainBranchReleaseData.version
        val updtURL = mainBranchReleaseData.downloadUrlPage

        val title = BuildConfig.NAME_SHORT + ": Plugin Update available"
        val message = "An update is available for the plugin - you are running $currVerName ${
            if (currIntegrated) "(Bundled Java) " else ""
        }and a newer recommended version ($updtVerName) is available at\n$updtURL"

        val notifMainDownloadInBrowser =
            NotificationHelper.UpdateOptionIDs.MAIN_DOWNLOAD_BROWSER.id
        val notifMainDownloadCopyLink =
            NotificationHelper.UpdateOptionIDs.MAIN_DOWNLOAD_COPY_LINK.id
        val notifMainPageInBrowser = NotificationHelper.UpdateOptionIDs.MAIN_PAGE_BROWSER.id
        val notifMainPageCopyLink = NotificationHelper.UpdateOptionIDs.MAIN_PAGE_COPY_LINK.id

        val options: Array<TPNotificationOption> =
            arrayOf(
                TPNotificationOption(notifMainDownloadInBrowser, "Download in Browser"),
                TPNotificationOption(notifMainDownloadCopyLink, "Copy Download Link"),
                TPNotificationOption(notifMainPageInBrowser, "Open Download Page in Browser"),
                TPNotificationOption(notifMainPageCopyLink, "Copy Download Page Link")
            )

        // Assign Release Data to outer variable
        updateReleaseDataMain = mainBranchReleaseData

        // ID is <baseMainId>:<mainVer>
        val notificationID = "${NotificationHelper.UpdateIDs.MAIN.id}:${updtVerName}"

        // Send Notification
        veadotubePlugin.sendShowNotification(
            notificationID, title, message, options
        )
    }

    private fun notifyReleaseUpdateDev(devBranchReleaseData: ReleaseData) {
        val currVerName = BuildConfig.VERSION_NAME_BASE
        val currIntegrated = BuildConfig.USES_TP_BUNDLED_JRE

        val updtVerName = devBranchReleaseData.version
        val updtURL = devBranchReleaseData.downloadUrlPage

        val title = BuildConfig.NAME_SHORT + ": Plugin Update available"
        val message = "An update is available for the plugin - you are running $currVerName ${
            if (currIntegrated) "(Bundled Java) " else ""
        }and a newer recommended version ($updtVerName) is available at\n$updtURL"

        val notifDevDownloadInBrowser =
            NotificationHelper.UpdateOptionIDs.DEV_DOWNLOAD_BROWSER.id
        val notifDevDownloadCopyLink =
            NotificationHelper.UpdateOptionIDs.DEV_DOWNLOAD_COPY_LINK.id
        val notifDevPageInBrowser = NotificationHelper.UpdateOptionIDs.DEV_PAGE_BROWSER.id
        val notifDevPageCopyLink = NotificationHelper.UpdateOptionIDs.DEV_PAGE_COPY_LINK.id

        val options: Array<TPNotificationOption> =
            arrayOf(
                TPNotificationOption(notifDevDownloadInBrowser, "Download in Browser"),
                TPNotificationOption(notifDevDownloadCopyLink, "Copy Download Link"),
                TPNotificationOption(notifDevPageInBrowser, "Open Download Page in Browser"),
                TPNotificationOption(notifDevPageCopyLink, "Copy Download Page Link")
            )

        // Assign Release Data to outer variable
        updateReleaseDataDev = devBranchReleaseData

        // ID is <baseDevId>:<devVer>
        val notificationID = "${NotificationHelper.UpdateIDs.DEV.id}:${updtVerName}"

        // Send Notification
        veadotubePlugin.sendShowNotification(
            notificationID, title, message, options
        )
    }


    private fun notifyReleaseUpdateBoth(mainBranchReleaseData: ReleaseData, devBranchReleaseData: ReleaseData) {
        if (mainBranchReleaseData.versionSemantic > devBranchReleaseData.versionSemantic) {
            // If Main is newer than Dev, run notifyReleaseUpdateMain and return
            notifyReleaseUpdateMain(mainBranchReleaseData)
            return
        }

        // Dev is newer than Main - Give both options
        val currVerName = BuildConfig.VERSION_NAME_BASE
        val currIntegrated = BuildConfig.USES_TP_BUNDLED_JRE

        val updtVerName = mainBranchReleaseData.version
        val updtURL = mainBranchReleaseData.downloadUrlPage

        val updtVerNameDev = devBranchReleaseData.version
        val updtURLDev = devBranchReleaseData.downloadUrlPage


        val title = BuildConfig.NAME_SHORT + ": Plugin Updates available"
        val message = buildString {
            append("Updates are available for the plugin - you are running ")
            append(currVerName)
            if (currIntegrated) append(" (Bundled Java).")
            else append(".")
            append("\nNewer Dev version ($updtVerNameDev) is available at\n$updtURLDev")
            append("\nNewer Main version ($updtVerName) is available at\n$updtURL")
        }

        val options: Array<TPNotificationOption> =
            arrayOf(
                TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.MAIN_DOWNLOAD_BROWSER.id,
                    "Download Main Version"
                ),
                /*TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.MAIN_DOWNLOAD_COPY_LINK.id,
                    "Copy Main Download Link"
                ),*/
                TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.MAIN_PAGE_BROWSER.id,
                    "Open Main Download Page"
                ),
                TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.MAIN_PAGE_COPY_LINK.id,
                    "Copy Main Page Link"
                ),

                TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.DEV_DOWNLOAD_BROWSER.id,
                    "Download Dev Version"
                ),
                /*TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.DEV_DOWNLOAD_COPY_LINK.id,
                    "Copy Dev Download Link"
                ),*/
                TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.DEV_PAGE_BROWSER.id,
                    "Open Dev Download Page"
                ),
                TPNotificationOption(
                    NotificationHelper.UpdateOptionIDs.DEV_PAGE_COPY_LINK.id,
                    "Copy Dev Page Link"
                )
            )

        // Assign Release Data to outer variable
        updateReleaseDataMain = mainBranchReleaseData

        // Assign Release Data to outer variable
        updateReleaseDataDev = devBranchReleaseData

        // ID is <baseBothId>:<mainVer>:<devVer>
        val notificationID =
            "${NotificationHelper.UpdateIDs.BOTH.id}:${updtVerName}:${updtVerNameDev}"

        // Send Notification
        veadotubePlugin.sendShowNotification(
            notificationID, title, message, options
        )
    }


    /**
     * Process Received Update Check Error
     */
    override fun onUpdateCheckError(exception: Exception) {
        // Error
        LOGGER.error { "Error Checking for Updates: ${exception.message}" }
        LOGGER.debug { "onUpdateCheckError - ${exception.message} : ${exception.stackTraceToString()}" }
        // TODO Add some logic to display notification if Check fails over several runs
    }


    fun sendTPNotification(
        notificationID: String,
        title: String,
        message: String,
        options: Array<TPNotificationOption>
    ) = veadotubePlugin.sendShowNotification(notificationID, title, message, options)

    /* End of functions for Update Checks */

}


