# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle (Main Branch)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: VeadotubeTouchPortalPlugin - Check out from repo
        uses: actions/checkout@v4
        with:
          path: ./VeadotubeTouchPortalPlugin

      - name: bleatkan - Check out from repo (Dependency)
        uses: actions/checkout@v4
        with:
          repository: DissonantAU/bleatkan
          ref: dev
          path: ./bleatkan

      - name: TouchPortalPluginSDK - Check out from repo (Dependency)
        uses: actions/checkout@v4
        with:
          repository: DissonantAU/TouchPortalPluginSDK
          ref: 8.3.1-RC
          path: ./TouchPortalPluginSDK

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Touch Portal Plugin SDK
      - name: TouchPortalPluginSDK - Change wrapper permissions
        run: chmod +x ./TouchPortalPluginSDK/gradlew

      - name: TouchPortalPluginSDK - Generate JARs with Gradle Wrapper
        run: ./TouchPortalPluginSDK/gradlew --project-dir ./TouchPortalPluginSDK/ Annotations:jar Helpers:jar AnnotationsProcessor:jar Library:jar Packager:jar

      - name: TouchPortalPluginSDK - Publish Packager Plugin to Maven Local with Wrapper
        run: ./TouchPortalPluginSDK/gradlew --project-dir ./TouchPortalPluginSDK/ Packager:publishToMavenLocal

      # Veadotube Touch Portal Plugin
      - name: VeadotubeTouchPortalPlugin - Change wrapper permissions
        run: chmod +x ./VeadotubeTouchPortalPlugin/gradlew

      - name: VeadotubeTouchPortalPlugin - Build with Gradle Wrapper
        run: ./VeadotubeTouchPortalPlugin/gradlew --project-dir ./VeadotubeTouchPortalPlugin/ build


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: VeadotubeTouchPortalPlugin - Check out from repo
        uses: actions/checkout@v4
        with:
          path: ./VeadotubeTouchPortalPlugin

      - name: TouchPortalPluginSDK - Check out from repo (Dependency)
        uses: actions/checkout@v4
        with:
          repository: DissonantAU/TouchPortalPluginSDK
          ref: 8.3.1-RC
          path: ./TouchPortalPluginSDK

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Touch Portal Plugin SDK
      - name: TouchPortalPluginSDK - Change wrapper permissions
        run: chmod +x ./TouchPortalPluginSDK/gradlew

      - name: TouchPortalPluginSDK - Publish Packager Plugin to Maven Local with Wrapper
        run: ./TouchPortalPluginSDK/gradlew --project-dir ./TouchPortalPluginSDK/ Packager:publishToMavenLocal
        #env:
        #  GITHUB_DEPENDENCY_GRAPH_ENABLED: false

      # Veadotube Touch Portal Plugin
      - name: VeadotubeTouchPortalPlugin - Change wrapper permissions
        run: chmod +x ./VeadotubeTouchPortalPlugin/gradlew

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: VeadotubeTouchPortalPlugin - Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          build-root-directory: ./VeadotubeTouchPortalPlugin/
